import {chromium} from 'playwright';
import {writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-webgpu']});
try{const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:5197/editor.html');await page.waitForFunction(()=>window.mapDiagnostics?.ready||window.mapDiagnostics?.errors.length);const idle=()=>page.evaluate(()=>editorTest.idle());await idle();
 await page.selectOption('#category','deadwood');const target=await page.locator('#viewport').boundingBox();await page.locator('.asset[data-preset="113"]').dragTo(page.locator('#viewport'),{targetPosition:{x:target.width*.5,y:target.height*.54}});await idle();assert.equal(await page.evaluate(()=>editorTest.getMap().objects.length),1,'drag/drop places one object');
 await page.fill('#x','0');await page.locator('#x').press('Tab');await page.fill('#z','0');await page.locator('#z').press('Tab');await idle();
 await page.fill('#rotation','45');await page.locator('#rotation').press('Tab');await page.fill('#scale','.8');await page.locator('#scale').press('Tab');await idle();assert.equal(await page.evaluate(()=>editorTest.getMap().objects[0].rotation),45);
 // Real viewport dragging, including asynchronous GPU picking.
 let p=await page.evaluate(()=>editorTest.project(0,0));let box=await page.locator('canvas').boundingBox();const sx=box.x+p.x/1024*box.width,sy=box.y+(p.y-10)/768*box.height;await page.mouse.move(sx,sy);await page.mouse.down();await page.waitForTimeout(250);await page.mouse.move(sx+55,sy+20,{steps:6});await page.mouse.up();await idle();assert(await page.evaluate(()=>Math.abs(editorTest.getMap().objects[0].x)>.2),'drag moves object');
 await page.click('#duplicate');await idle();assert.equal(await page.evaluate(()=>editorTest.getMap().objects.length),2);await page.click('#radiusTool');await page.locator('#radius').fill('8');await page.locator('#radius').dispatchEvent('input');p=await page.evaluate(()=>{const o=editorTest.getMap().objects[0];return editorTest.project(o.x,o.z);});await page.mouse.click(box.x+p.x/1024*box.width,box.y+p.y/768*box.height);await idle();assert.equal(await page.evaluate(()=>editorTest.getSelection().length),2,'radius selects both');
 const generations=await page.evaluate(()=>editorTest.generations);await page.click('#terrainTab');await page.locator('#radius').fill('3');await page.locator('#radius').dispatchEvent('input');await page.locator('#strength').fill('0.5');await page.mouse.move(box.x+p.x/1024*box.width,box.y+p.y/768*box.height);await page.mouse.down();await page.mouse.move(box.x+p.x/1024*box.width+18,box.y+p.y/768*box.height,{steps:6});await page.mouse.up();await idle();assert(await page.evaluate(()=>Math.max(...editorTest.getMap().terrain)>.1),'terrain painted');assert.equal(await page.evaluate(()=>editorTest.generations),generations,'terrain changes reuse cached assets');assert(Number(await page.locator('#groundHeight').textContent())>.1,'selected object follows terrain');await page.screenshot({path:'artifacts/editor-terrain.png',fullPage:true});
 const terrain=await page.evaluate(()=>editorTest.getMap().terrain);await page.click('#undo');await idle();assert.equal(await page.evaluate(()=>Math.max(...editorTest.getMap().terrain)),0);await page.click('#redo');await idle();assert.deepEqual(await page.evaluate(()=>editorTest.getMap().terrain),terrain);
 const saved=await page.evaluate(()=>editorTest.getMap());const downloadEvent=page.waitForEvent('download');await page.click('#save');const download=await downloadEvent;await download.saveAs('artifacts/editor-roundtrip.json');assert.deepEqual(JSON.parse(await readFile('artifacts/editor-roundtrip.json','utf8')),saved);await page.click('#new');await page.click('#createMap');await idle();assert.equal(await page.evaluate(()=>editorTest.getMap().objects.length),0);await page.locator('#file').setInputFiles('artifacts/editor-roundtrip.json');await page.waitForFunction(()=>editorTest.getMap().objects.length===2);await idle();assert.deepEqual(await page.evaluate(()=>editorTest.getMap()),saved);
 await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"wrong"}')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.startsWith('Could not load map:'));assert.deepEqual(await page.evaluate(()=>editorTest.getMap()),saved,'invalid import leaves current map intact');
 const terrainDownload=page.waitForEvent('download');await page.click('#saveTerrain');await (await terrainDownload).saveAs('artifacts/editor-terrain-roundtrip.json');await page.click('#resetTerrain');await idle();await page.locator('#terrainFile').setInputFiles('artifacts/editor-terrain-roundtrip.json');await page.waitForFunction(()=>Math.max(...editorTest.getMap().terrain)>.1);await idle();assert.deepEqual(await page.evaluate(()=>editorTest.getMap().terrain),terrain);
 await page.reload();await page.waitForFunction(()=>mapDiagnostics?.ready);await page.evaluate(()=>editorTest.idle());assert.equal(await page.evaluate(()=>editorTest.getMap().objects.length),2,'autosave persists reload');
 await page.click('#example');await idle();await page.screenshot({path:'artifacts/editor-scene.png',fullPage:true});if(errors.length)throw Error(errors.join('\n'));await writeFile('artifacts/editor-validation.json',JSON.stringify({passed:['drag/drop placement','transform inspector','GPU pick and drag','duplicate','radius multi-selection','terrain brush','terrain attachment','cache reuse','undo redo terrain stroke','map file roundtrip','terrain-only roundtrip','invalid import preserves map','autosave reload','example render'],errors},null,2));console.log('Editor: drag/drop, picking, movement, radius selection, terrain, attachment, cache, history, save/load and autosave passed.');
}finally{await browser.close();}

