import {BUILD_TYPES,BUILD_MATERIALS,BUILD_LIMIT,newBuilding,buildingSockets,localToWorld,validateBuildings} from './building-model.js';
import {terrainHeight} from './map-model.js';
import {surfaceRay,ray,projectPoint} from './scene-camera.js';
export function buildingEditor({getMap,commit,previewPlacement,previewMap,view,activate,request,toast,frame,pick}){
 const $=id=>document.getElementById(id);let selected=null,type=0,placing=false,rotation=0,material=0,offset=.6,drag=null,last=null,template=null,nativeDrag=false,lastScreen=null;
 const chosen=()=>getMap().buildings?.find(p=>p.id===selected);
 const nextId=()=>Math.max(0,...(getMap().buildings??[]).map(p=>p.id))+1;
 const change=fn=>{const m=getMap(),buildings=structuredClone(m.buildings??[]);fn(buildings);commit({...m,buildings});refresh();};
 for(const [i,label] of BUILD_MATERIALS.entries()){const option=document.createElement('option');option.value=i;option.textContent=label;$('buildMaterial').append(option);}
 for(const [i,label] of BUILD_TYPES.entries()){const b=document.createElement('button');b.textContent=label;b.dataset.buildType=i;b.draggable=true;b.onclick=()=>choose(i);b.ondragstart=e=>{nativeDrag=true;choose(i);e.dataTransfer.setData('application/x-leaf-building',String(i));e.dataTransfer.effectAllowed='copy';};b.ondragend=()=>{nativeDrag=false;previewPlacement(null);request();};$('buildingParts').append(b);}
 function choose(value){if((getMap().buildings?.length??0)>=BUILD_LIMIT){toast('Building limit reached: 2,048 pieces.');return;}template=null;type=value;selected=null;placing=true;offset=type<2?.6:0;activate();refresh();previewPlacement(null);request();}
 function select(id){selected=id;placing=false;previewPlacement(null);activate();refresh();request();}
 function refresh(){if(selected&&!chosen())selected=null;const p=chosen();view.buildSelected=selected??0;$('buildStatus').textContent=placing?'Click or drag to place. R rotates. Esc finishes.':p?'Drag the piece to move it. Change each piece below.':'Choose a part below, or select an existing piece.';$('buildName').value=p?.name??BUILD_TYPES[type];$('buildMaterial').value=p?.material??material;$('buildOffset').value=p?+(p.level-terrainHeight(getMap(),p.x,p.z)).toFixed(3):offset;for(const k of ['width','depth','height','rotation'])$('build'+k[0].toUpperCase()+k.slice(1)).value=p?.[k]??newBuilding(1,type,0,0)[k];if(!p)$('buildRotation').value=rotation;$('buildSupports').value=p?.support??(type===1?1:0);$('buildVisible').checked=p?.visible??true;$('buildSupports').closest('label').hidden=!(p?p.type<2:type<2);for(const id of ['buildName','buildWidth','buildDepth','buildHeight','buildSupports','buildVisible','deleteBuilding','frameBuilding','duplicateBuilding'])$(id).disabled=!p;$('buildList').replaceChildren();for(const piece of getMap().buildings??[]){const b=document.createElement('button');b.textContent=piece.name;b.className=piece.id===selected?'active':'';b.onclick=()=>select(piece.id);$('buildList').append(b);}for(const b of $('buildingParts').children)b.classList.toggle('active',placing&&Number(b.dataset.buildType)===type);}
 for(const [id,key] of [['buildName','name'],['buildWidth','width'],['buildDepth','depth'],['buildHeight','height'],['buildRotation','rotation'],['buildSupports','support'],['buildMaterial','material'],['buildVisible','visible'],['buildOffset','level']])$(id).onchange=()=>{const p=chosen();let value=key==='name'?$(id).value:key==='visible'?$(id).checked:Number($(id).value);if(!p){if(key==='material')material=value;if(key==='rotation')rotation=((value%360)+360)%360;if(key==='level')offset=value;refresh();if(placing&&lastScreen)hover(lastScreen);return;}if(key==='rotation')value=((value%360)+360)%360;if(key==='level')value+=terrainHeight(getMap(),p.x,p.z);change(list=>{list.find(q=>q.id===p.id)[key]=value;});request();};
 $('deleteBuilding').onclick=()=>{if(chosen())change(list=>list.splice(list.findIndex(p=>p.id===selected),1));selected=null;refresh();request();};
 $('frameBuilding').onclick=()=>{const p=chosen();if(p)frame([p.x,p.level+p.height*.4,p.z],Math.max(p.width,p.depth,p.height)*.8);};
 $('duplicateBuilding').onclick=()=>{const p=chosen();if(!p)return;if(getMap().buildings.length>=BUILD_LIMIT){toast('Building limit reached: 2,048 pieces.');return;}type=p.type;material=p.material;rotation=p.rotation;offset=p.level-terrainHeight(getMap(),p.x,p.z);template={...p};last=null;selected=null;placing=true;refresh();request();};
 $('buildSelect').onclick=()=>{placing=false;previewPlacement(null);refresh();request();};
 $('buildRotate').onclick=()=>rotate();
 function rotate(){const p=chosen();if(p)change(list=>{const q=list.find(q=>q.id===p.id);q.rotation=(q.rotation+90)%360;});else rotation=(rotation+90)%360;refresh();if(placing&&lastScreen)hover(lastScreen);request();}
 function candidate(screen,moving=null){const map=getMap(),world=surfaceRay(view,map,screen);let p=moving?{...moving}:template?{...template,id:nextId(),x:world.x,z:world.z}:newBuilding(nextId(),type,world.x,world.z,terrainHeight(map,world.x,world.z));if(!moving){p.material=material;p.rotation=rotation;p.level=terrainHeight(map,p.x,p.z)+offset;}else{const d=ray(view,screen);const t=(p.level-view.position[1])/d[1];if(t>0&&Number.isFinite(t)){p.x=view.position[0]+d[0]*t+(drag?.offsetX??0);p.z=view.position[2]+d[2]*t+(drag?.offsetZ??0);}else if(world.hit){p.x=world.x;p.z=world.z;}}
 let best=48*48,snap=null;if($('buildSnap').checked)for(const target of map.buildings??[]){if(!target.visible||target.id===moving?.id)continue;for(const socket of buildingSockets(target,p)){const v=projectPoint(view,[socket.x,socket.level,socket.z]);const distance=(v.x-screen.x)**2+(v.y-screen.y)**2;if(v.depth>.05&&distance<best){best=distance;snap=socket;}}}if(snap){Object.assign(p,snap);if(!moving&&Number.isFinite(snap.stairTop)){const foot=localToWorld(p,0,-p.depth/2),ground=terrainHeight(map,foot.x,foot.z),rise=snap.stairTop-ground;if(rise>=.15&&rise<=32){p.level=ground;p.height=rise;}}}else if(!world.hit&&!moving)return null;const half=map.extent/2;p.x=Math.max(-half,Math.min(half,p.x));p.z=Math.max(-half,Math.min(half,p.z));return p;}
 function hover(screen){lastScreen=screen;if(drag){const p=candidate(screen,drag.piece);if(!p)return true;const m={...getMap(),buildings:drag.base.buildings.map(q=>q.id===p.id?p:q)};try{validateBuildings(m.buildings,m.extent);previewMap(m);}catch(e){toast(e.message);}return true;}if(!placing)return false;if((getMap().buildings?.length??0)>=BUILD_LIMIT){previewPlacement(null);last=null;return true;}last=candidate(screen);if(last){try{validateBuildings([last],getMap().extent);}catch(e){toast(e.message);last=null;}}previewPlacement(last?{...getMap(),buildings:[...(getMap().buildings??[]),last]}:null);return true;}
 function place(screen){hover(screen);if(!last)return;const p=last;try{const buildings=[...(getMap().buildings??[]),p];validateBuildings(buildings,getMap().extent);if(buildings.slice(0,-1).some(q=>q.type===p.type&&Math.hypot(q.x-p.x,q.z-p.z,q.level-p.level)<.05&&q.rotation===p.rotation)){toast('A matching building piece is already there.');return;}commit({...getMap(),buildings});previewPlacement(null);selected=p.id;placing=false;last=null;refresh();request();}catch(e){toast(e.message);}}
 async function down(screen,stillDown){if(placing){place(screen);return;}const id=await pick(screen);if(!id){selected=null;refresh();request();return;}select(id);const p=chosen();if(p&&stillDown()){const d=ray(view,screen),t=(p.level-view.position[1])/d[1];drag={base:structuredClone(getMap()),piece:structuredClone(p),offsetX:t>0?p.x-view.position[0]-d[0]*t:0,offsetZ:t>0?p.z-view.position[2]-d[2]*t:0};}}
 function end(){if(drag){drag=null;commit(getMap());refresh();}}
 function cancel(){drag=null;placing=false;selected=null;last=null;view.buildSelected=0;previewPlacement(null);refresh();}
 function overlay(){const p=chosen()??(placing?last:null);if(!p)return '';let sockets='';if(placing&&$('buildSnap').checked){let count=0;for(const target of getMap().buildings??[]){if(!target.visible)continue;for(const s of buildingSockets(target,p)){const v=projectPoint(view,[s.x,s.level,s.z]);if(v.depth>.05&&v.x>=0&&v.x<=1024&&v.y>=0&&v.y<=768&&count++<96)sockets+='<circle cx="'+v.x+'" cy="'+v.y+'" r="4" fill="#103936aa" stroke="#8aebdc"/>';}}}const pts=[];for(const [x,z] of [[-1,-1],[1,-1],[1,1],[-1,1],[-1,-1]]){const q=localToWorld(p,x*p.width/2,z*p.depth/2);const v=projectPoint(view,[q.x,p.level+.025,q.z]);if(v.depth>.05)pts.push(v.x+','+v.y);}return sockets+'<polyline points="'+pts.join(' ')+'" fill="none" stroke="#f6d88f" stroke-width="2"/>';}
 return {choose,select,refresh,hover,down,place,end,cancel,overlay,rotate,isPlacing:()=>placing,getSelected:chosen,isDragging:()=>nativeDrag};
}
