export const BUILD_TYPES=['Platform','Foundation','Wall','Half wall','Doorway','Window wall','Stairs','Ramp','Pitched roof','Flat roof','Pillar','Railing','Beam'];
export const BUILD_MATERIALS=['Wood','Stone','Mud','Brick','Plaster','Slate','Thatch'];
export const BUILD_LIMIT=2048;
export function newBuilding(id,type,x,z,ground=0){return {id,name:BUILD_TYPES[type]+' '+id,type,material:type===1?1:0,x,z,level:ground+(type<2?.6:0),rotation:0,width:type===10?.35:4,depth:[2,3,4,5,11,12].includes(type)?.22:type===10?.35:4,height:type<2?.25:type===3?1.5:type===8?1.5:type===9?.2:type===11?1:type===12?.25:3,visible:true,support:type===1?1:0};}
export function validateBuildings(value,extent){if(value===undefined)return [];if(!Array.isArray(value)||value.length>BUILD_LIMIT)throw Error('A map supports up to 2,048 building pieces.');const ids=new Set();return value.map(p=>{if(!p||!Number.isInteger(p.id)||p.id<1||ids.has(p.id)||typeof p.name!=='string'||p.name.length>80||typeof p.visible!=='boolean'||!Number.isInteger(p.type)||p.type<0||p.type>=BUILD_TYPES.length||!Number.isInteger(p.material)||p.material<0||p.material>=BUILD_MATERIALS.length||![0,1,2].includes(p.support))throw Error('Invalid building piece.');ids.add(p.id);for(const k of ['x','z','level','rotation','width','depth','height'])if(!Number.isFinite(p[k]))throw Error('Building dimensions must be finite.');if(Math.abs(p.x)>extent/2||Math.abs(p.z)>extent/2||p.level< -512||p.level>4096||p.rotation<0||p.rotation>=360||p.width<.2||p.width>32||p.depth<.15||p.depth>32||p.height<.15||p.height>32)throw Error('Building piece is outside supported dimensions.');return Object.fromEntries(['id','name','type','material','x','z','level','rotation','width','depth','height','visible','support'].map(k=>[k,p[k]]));});}
export function localToWorld(p,x,z){const a=p.rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return {x:p.x+x*c-z*s,z:p.z+x*s+z*c};}
export function buildingSockets(target,piece){const out=[],deck=[0,1,9].includes(target.type);const add=(x,z,level,rotation)=>out.push({...localToWorld(target,x,z),level,rotation:(rotation+360)%360});
 if(deck){if(piece.type<2){add((target.width+piece.width)/2,0,target.level,target.rotation);add(-(target.width+piece.width)/2,0,target.level,target.rotation);add(0,(target.depth+piece.depth)/2,target.level,target.rotation);add(0,-(target.depth+piece.depth)/2,target.level,target.rotation);}
 else if([2,3,4,5,11].includes(piece.type)){add(0,target.depth/2,target.level,target.rotation);add(0,-target.depth/2,target.level,target.rotation+180);add(target.width/2,0,target.level,target.rotation+90);add(-target.width/2,0,target.level,target.rotation+270);}
 else if([6,7].includes(piece.type)){add(0,-(target.depth+piece.depth)/2,target.level-piece.height,target.rotation);add(0,(target.depth+piece.depth)/2,target.level-piece.height,target.rotation+180);add((target.width+piece.depth)/2,0,target.level-piece.height,target.rotation+90);add(-(target.width+piece.depth)/2,0,target.level-piece.height,target.rotation+270);}
 else if([8,9].includes(piece.type))add(0,0,target.level+3,target.rotation);
 else for(const x of [-target.width/2,target.width/2])for(const z of [-target.depth/2,target.depth/2])add(x,z,target.level,target.rotation);
 }else{if([8,9,12].includes(piece.type)){add(0,-piece.depth/2,target.level+target.height,target.rotation);add(0,piece.depth/2,target.level+target.height,target.rotation);}else{add((target.width+piece.width)/2,0,target.level,target.rotation);add(-(target.width+piece.width)/2,0,target.level,target.rotation);add(0,0,target.level+target.height,target.rotation);}}
 if([6,7].includes(piece.type)&&deck)for(const socket of out)socket.stairTop=target.level;return out;}
