import {BUILD_TYPES,BUILD_MATERIALS,BUILD_LIMIT,newBuilding,buildingSockets,localToWorld,validateBuildings,isDeck,isRoof} from './building-model.js';
import {terrainHeight} from './map-model.js';
import {surfaceRay,ray,projectPoint} from './scene-camera.js';
export function buildingEditor({getMap,commit,previewPlacement,previewMap,view,activate,request,toast,frame,pick}){
 const $=id=>document.getElementById(id);let selected=null,type=0,placing=false,rotation=0,material=0,offset=.6,drag=null,last=null,template=null,nativeDrag=false,lastScreen=null,lastSnap=null;
 const chosen=()=>getMap().buildings?.find(p=>p.id===selected);
 const nextId=()=>Math.max(0,...(getMap().buildings??[]).map(p=>p.id))+1;
 const change=fn=>{const m=getMap(),buildings=structuredClone(m.buildings??[]);fn(buildings);commit({...m,buildings});refresh();};
 for(const [i,label] of BUILD_MATERIALS.entries()){const option=document.createElement('option');option.value=i;option.textContent=label;$('buildMaterial').append(option);}
 for(const [i,label] of BUILD_TYPES.entries()){const b=document.createElement('button');b.innerHTML=partIcon(i)+'<span>'+label+'</span>';b.title=label+' - drag into the viewport or click to place';b.dataset.buildType=i;b.dataset.category=[18,19,20,24].includes(i)?'round':i===17||[21,22,23].includes(i)?'roof':i>=13?'castle':i<2?'base':[6,7].includes(i)?'access':[8,9].includes(i)?'roof':'wall';b.draggable=true;b.onclick=()=>choose(i);b.ondragstart=e=>{nativeDrag=true;choose(i);e.dataTransfer.setData('application/x-leaf-building',String(i));e.dataTransfer.effectAllowed='copy';};b.ondragend=()=>{nativeDrag=false;previewPlacement(null);request();};$('buildingParts').append(b);}
 function partIcon(i){const shapes=['M4 20L24 12L44 20L24 28Z','M4 14L24 6L44 14V26L24 32L4 26Z','M8 28V6H40V28Z','M8 28V16H40V28Z','M8 28V6H40V28H29V15H19V28Z','M8 28V6H40V28ZM19 12V22H29V12Z','M6 28V22H14V16H22V10H30V4H40V28Z','M6 28L40 6V28Z','M3 21L24 3L45 21L40 24L24 10L8 24Z','M4 12H44V20H4Z','M19 3H29V29H19Z','M5 8H43V12H5ZM5 19H43V22H5ZM7 6V29M24 6V29M41 6V29','M4 12H44V20H4Z','M4 28V5H11V13H18V5H26V13H33V5H42V28Z','M5 28V4H43V28H34V19Q24 3 14 19V28Z','M8 28L20 4H32V28Z','M6 28V4H42V28ZM22 11V23H26V11Z','M4 28L24 4L44 28Z','M4 13C4 2 44 2 44 13V24C44 35 4 35 4 24ZM4 13C4 24 44 24 44 13','M5 8C5 1 43 1 43 8V26C43 33 5 33 5 26ZM5 8C5 16 43 16 43 8','M5 8C5 1 43 1 43 8V26L30 29V18H18V29L5 26Z','M3 27L24 3L45 27Q24 36 3 27Z','M3 26L24 3L45 26L24 32ZM24 3V32','M3 25L15 8H32L45 25L24 32ZM15 8L24 32L32 8','M5 29V7Q24 0 43 7V29Q24 20 5 29Z'];return '<svg viewBox="0 0 48 34" aria-hidden="true"><path fill-rule="evenodd" d="'+shapes[i]+'"/></svg>';}
 $('buildCategory').onchange=()=>{for(const b of $('buildingParts').children)b.hidden=$('buildCategory').value!=='all'&&b.dataset.category!==$('buildCategory').value;};
 $('buildSearch').oninput=()=>refresh();
 for(const id of ['buildPlane','buildLevel','buildGrid'])$(id).onchange=()=>{$('buildLevelLabel').hidden=$('buildPlane').value!=='level';if(placing&&lastScreen)hover(lastScreen);request();};
 $('buildUseLevel').onclick=()=>{const p=chosen();if(!p)return;$('buildPlane').value='level';$('buildLevel').value=isDeck(p.type)?p.level:p.level+p.height;$('buildLevelLabel').hidden=false;toast('Placement floor set. Choose a part to build at this height.');};
 $('frameBuildings').onclick=()=>{const ps=(getMap().buildings??[]).filter(p=>p.visible);if(!ps.length)return;const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const p of ps){const r=Math.hypot(p.width,p.depth)/2;for(const [i,a,b]of [[0,p.x-r,p.x+r],[1,p.level-(isDeck(p.type)?p.height:0),p.level+p.height],[2,p.z-r,p.z+r]]){lo[i]=Math.min(lo[i],a);hi[i]=Math.max(hi[i],b);}}const centre=lo.map((v,i)=>(v+hi[i])/2);frame(centre,Math.hypot(...hi.map((v,i)=>(v-lo[i])/2)));};
 function choose(value){if((getMap().buildings?.length??0)>=BUILD_LIMIT){toast('Building limit reached: 2,048 pieces.');return;}type=value;template=newBuilding(1,type,0,0);if(type>=13||isRoof(type))material=isRoof(type)?5:1;selected=null;placing=true;last=null;lastSnap=null;offset=isDeck(type)?.6:0;activate();refresh();previewPlacement(null);request();}
 function select(id){selected=id;placing=false;previewPlacement(null);activate();refresh();request();}
 function refresh(){if(selected&&!chosen())selected=null;const p=chosen();view.buildSelected=selected??0;$('buildStatus').textContent=placing?'Click or drag to place. R rotates. Esc finishes.':p?'Drag the piece to move it. Change each piece below.':'Choose a part below, or select an existing piece.';$('buildName').value=p?.name??BUILD_TYPES[type];$('buildMaterial').value=p?.material??material;$('buildOffset').value=p?+(p.level-terrainHeight(getMap(),p.x,p.z)).toFixed(3):offset;for(const k of ['width','depth','height','rotation'])$('build'+k[0].toUpperCase()+k.slice(1)).value=p?.[k]??template?.[k]??newBuilding(1,type,0,0)[k];if(!p)$('buildRotation').value=rotation;$('buildSupports').value=p?.support??template?.support??(type===1||type===18?1:0);$('buildVisible').checked=p?.visible??true;$('buildSupports').options[0].disabled=(p?.type??type)===18;$('buildSupports').closest('label').hidden=!(p?isDeck(p.type):isDeck(type));for(const id of ['buildName','buildVisible','deleteBuilding','frameBuilding','duplicateBuilding','buildUseLevel'])$(id).disabled=!p;for(const id of ['buildWidth','buildDepth','buildHeight','buildSupports'])$(id).disabled=!p&&!placing;$('buildList').replaceChildren();for(const piece of getMap().buildings??[]){if(!piece.name.toLowerCase().includes($('buildSearch').value.toLowerCase()))continue;const b=document.createElement('button');b.textContent=piece.name;b.className=piece.id===selected?'active':'';b.onclick=()=>select(piece.id);$('buildList').append(b);}for(const b of $('buildingParts').children)b.classList.toggle('active',placing&&Number(b.dataset.buildType)===type);}
 for(const [id,key] of [['buildName','name'],['buildWidth','width'],['buildDepth','depth'],['buildHeight','height'],['buildRotation','rotation'],['buildSupports','support'],['buildMaterial','material'],['buildVisible','visible'],['buildOffset','level']])$(id).onchange=()=>{const p=chosen();let value=key==='name'?$(id).value:key==='visible'?$(id).checked:Number($(id).value);if(!p){if(template&&['width','depth','height','support'].includes(key))template[key]=value;if(key==='material')material=value;if(key==='rotation')rotation=((value%360)+360)%360;if(key==='level')offset=value;refresh();if(placing&&lastScreen)hover(lastScreen);return;}if(key==='rotation')value=((value%360)+360)%360;if(key==='level')value+=terrainHeight(getMap(),p.x,p.z);change(list=>{list.find(q=>q.id===p.id)[key]=value;});request();};
 $('deleteBuilding').onclick=()=>{if(chosen())change(list=>list.splice(list.findIndex(p=>p.id===selected),1));selected=null;refresh();request();};
 $('frameBuilding').onclick=()=>{const p=chosen();if(p)frame([p.x,p.level+p.height*.4,p.z],Math.max(p.width,p.depth,p.height)*.8);};
 $('duplicateBuilding').onclick=()=>{const p=chosen();if(!p)return;if(getMap().buildings.length>=BUILD_LIMIT){toast('Building limit reached: 2,048 pieces.');return;}type=p.type;material=p.material;rotation=p.rotation;offset=p.level-terrainHeight(getMap(),p.x,p.z);template={...p};last=null;selected=null;placing=true;refresh();request();};
 $('buildSelect').onclick=()=>{placing=false;previewPlacement(null);refresh();request();};
 $('buildRotate').onclick=()=>rotate();
 function rotate(){const p=chosen();if(p)change(list=>{const q=list.find(q=>q.id===p.id);q.rotation=(q.rotation+90)%360;});else rotation=(rotation+90)%360;refresh();if(placing&&lastScreen)hover(lastScreen);request();}
 function candidate(screen,moving=null){lastSnap=null;const map=getMap(),world=surfaceRay(view,map,screen);let p=moving?{...moving}:template?{...template,id:nextId(),x:world.x,z:world.z}:newBuilding(nextId(),type,world.x,world.z,terrainHeight(map,world.x,world.z));if(!moving){p.material=material;p.rotation=rotation;p.level=terrainHeight(map,p.x,p.z)+offset;}else{const d=ray(view,screen);const t=(p.level-view.position[1])/d[1];if(t>0&&Number.isFinite(t)){p.x=view.position[0]+d[0]*t+(drag?.offsetX??0);p.z=view.position[2]+d[2]*t+(drag?.offsetZ??0);}else if(world.hit){p.x=world.x;p.z=world.z;}}
 if(!moving&&$('buildPlane').value==='level'){const d=ray(view,screen),level=Number($('buildLevel').value),t=(level-view.position[1])/d[1];if(t<=0||!Number.isFinite(t)||!Number.isFinite(level))return null;p.x=view.position[0]+d[0]*t;p.z=view.position[2]+d[2]*t;p.level=level;}const grid=Number($('buildGrid').value);if(grid>0){p.x=Math.round(p.x/grid)*grid;p.z=Math.round(p.z/grid)*grid;if(!moving&&$('buildPlane').value==='terrain')p.level=terrainHeight(map,p.x,p.z)+offset;}
 const socketKey=(t,x,z,y,r)=>[t,x.toFixed(3),z.toFixed(3),y.toFixed(3),(r+360)%360].join(':');const occupied=new Set((map.buildings??[]).filter(q=>q.id!==moving?.id&&q.visible).map(q=>socketKey(q.type,q.x,q.z,q.level,q.rotation)));let best=48*48,snap=null;if($('buildSnap').checked)for(const target of map.buildings??[]){if(!target.visible||target.id===moving?.id)continue;for(const socket of buildingSockets(target,p)){if(occupied.has(socketKey(p.type,socket.x,socket.z,socket.level,socket.rotation)))continue;const v=projectPoint(view,[socket.x,socket.level,socket.z]);const distance=(v.x-screen.x)**2+(v.y-screen.y)**2;if(v.depth>.05&&distance<best){best=distance;snap=socket;}}}if(snap){lastSnap=snap;Object.assign(p,snap);if(!moving&&Number.isFinite(snap.stairTop)){const foot=localToWorld(p,0,-p.depth/2),ground=terrainHeight(map,foot.x,foot.z),rise=snap.stairTop-ground;if(rise>=.15&&rise<=32){p.level=ground;p.height=rise;}}}else if(!world.hit&&!moving&&$('buildPlane').value!=='level')return null;const half=map.extent/2;p.x=Math.max(-half,Math.min(half,p.x));p.z=Math.max(-half,Math.min(half,p.z));return p;}
 function hover(screen){lastScreen=screen;if(drag){const p=candidate(screen,drag.piece);if(!p)return true;const m={...getMap(),buildings:drag.base.buildings.map(q=>q.id===p.id?p:q)};try{validateBuildings(m.buildings,m.extent);previewMap(m);}catch(e){toast(e.message);}return true;}if(!placing)return false;if((getMap().buildings?.length??0)>=BUILD_LIMIT){previewPlacement(null);last=null;return true;}last=candidate(screen);if(last){try{validateBuildings([last],getMap().extent);}catch(e){toast(e.message);last=null;}}view.buildSelected=last?.id??0;if(last)$('buildStatus').textContent=BUILD_TYPES[last.type]+' | '+last.width+' x '+last.depth+' x '+last.height+' m | Y '+last.level.toFixed(2)+' m'+(lastSnap?' | Snapped':'');previewPlacement(last?{...getMap(),buildings:[...(getMap().buildings??[]),last]}:null);return true;}
 function place(screen){hover(screen);if(!last)return;const p=last;try{const buildings=[...(getMap().buildings??[]),p];validateBuildings(buildings,getMap().extent);if(buildings.slice(0,-1).some(q=>q.type===p.type&&Math.hypot(q.x-p.x,q.z-p.z,q.level-p.level)<.05&&q.rotation===p.rotation)){toast('A matching building piece is already there.');return;}commit({...getMap(),buildings});previewPlacement(null);selected=$('buildRepeat').checked?null:p.id;placing=$('buildRepeat').checked;last=null;refresh();request();}catch(e){toast(e.message);}}
 async function down(screen,stillDown){if(placing){place(screen);return;}const id=await pick(screen);if(!id){selected=null;refresh();request();return;}select(id);const p=chosen();if(p&&stillDown()){const d=ray(view,screen),t=(p.level-view.position[1])/d[1];drag={base:structuredClone(getMap()),piece:structuredClone(p),offsetX:t>0?p.x-view.position[0]-d[0]*t:0,offsetZ:t>0?p.z-view.position[2]-d[2]*t:0};}}
 function end(){if(drag){drag=null;commit(getMap());refresh();}}
 function cancel(){drag=null;placing=false;selected=null;last=null;view.buildSelected=0;previewPlacement(null);refresh();}
 function overlay(){const p=chosen()??(placing?last:null);if(!p)return '';let svg='';if(placing&&$('buildSnap').checked){let count=0;for(const target of getMap().buildings??[]){if(!target.visible||Math.hypot(target.x-p.x,target.z-p.z)>Math.max(12,p.width+target.width))continue;for(const s of buildingSockets(target,p)){const v=projectPoint(view,[s.x,s.level,s.z]);if(v.depth>.05&&v.x>=0&&v.x<=1024&&v.y>=0&&v.y<=768&&count++<64)svg+='<circle cx="'+v.x+'" cy="'+v.y+'" r="3" fill="#103936aa" stroke="#8aebdc"/>';}}}
 const bottom=p.level-(isDeck(p.type)?p.height:0),top=isDeck(p.type)?p.level:p.level+p.height,points=[];for(const y of [bottom,top])for(const [x,z]of [[-1,-1],[1,-1],[1,1],[-1,1]]){const q=localToWorld(p,x*p.width/2,z*p.depth/2);points.push(projectPoint(view,[q.x,y,q.z]));}const edge=(a,b)=>{if(a.depth>.05&&b.depth>.05)svg+='<line x1="'+a.x+'" y1="'+a.y+'" x2="'+b.x+'" y2="'+b.y+'" stroke="#ffe6a1" stroke-width="2"/>';};if([18,19,20,21,24].includes(p.type)){const span=p.type===24?Math.PI/2:Math.PI*2,arc=(angle,y)=>{const q=localToWorld(p,Math.cos(angle)*p.width/2,Math.sin(angle)*p.depth/2);return projectPoint(view,[q.x,y,q.z]);};for(let i=0;i<32;i++){edge(arc(i*span/32,bottom),arc((i+1)*span/32,bottom));if(p.type!==21)edge(arc(i*span/32,top),arc((i+1)*span/32,top));}for(let i=0;i<=4;i++)edge(arc(i*span/4,bottom),p.type===21?projectPoint(view,[p.x,top,p.z]):arc(i*span/4,top));}else{for(let i=0;i<4;i++){edge(points[i],points[(i+1)%4]);edge(points[i+4],points[(i+1)%4+4]);edge(points[i],points[i+4]);}}const a=projectPoint(view,[p.x,top+.05,p.z]),q=localToWorld(p,0,-p.depth/2-1),b=projectPoint(view,[q.x,top+.05,q.z]);edge(a,b);if(b.depth>.05)svg+='<circle cx="'+b.x+'" cy="'+b.y+'" r="4" fill="#ffe6a1"/>';if(lastSnap&&placing){const v=projectPoint(view,[lastSnap.x,lastSnap.level,lastSnap.z]);if(v.depth>.05)svg+='<circle cx="'+v.x+'" cy="'+v.y+'" r="9" fill="none" stroke="#85f0da" stroke-width="3"/>';}
 if(a.depth>.05)svg+='<text x="'+a.x+'" y="'+(a.y-14)+'" text-anchor="middle" fill="#fff2cb" stroke="#142026" stroke-width="4" paint-order="stroke" font-size="13">'+p.width+' x '+p.depth+' x '+p.height+' m / Y '+p.level.toFixed(2)+'</text>';return svg;}

 return {choose,select,refresh,hover,down,place,end,cancel,overlay,rotate,isPlacing:()=>placing,getSelected:chosen,isDragging:()=>nativeDrag};
}
