export const PATH_TYPES=['Sand','Dirt','Stone','Pebbles','Gravel','Cobblestone','Brick','Flagstone','Slate','Limestone','Clay','Mud','Wood chips','Worn grass'];
export const PATH_LIMITS={paths:32,nodes:128,edges:192,segments:16384,references:262144};
export function validatePaths(value,extent){if(value===undefined)return [];if(!Array.isArray(value)||value.length>32)throw Error('Up to 32 paths are supported.');if(value.length===0)return [];const ids=new Set();const paths=value.map(p=>{if(!p||!Number.isInteger(p.id)||p.id<1||ids.has(p.id)||typeof p.name!=='string'||p.name.length>80||typeof p.visible!=='boolean'||!Number.isInteger(p.material)||p.material<0||p.material>=PATH_TYPES.length||!Number.isFinite(p.width)||p.width<.25||p.width>64||!Number.isFinite(p.softness)||p.softness<0||p.softness>4||!Number.isInteger(p.seed)||p.seed<0||p.seed>4294967295)throw Error('Invalid path settings.');ids.add(p.id);if(!Array.isArray(p.nodes)||p.nodes.length<2||p.nodes.length>128||!Array.isArray(p.edges)||p.edges.length<1||p.edges.length>192)throw Error('Paths need 2-128 nodes and 1-192 connections.');const nodes=new Set();const point=v=>v&&Number.isFinite(v.x)&&Number.isFinite(v.z)&&Math.abs(v.x)<=extent/2&&Math.abs(v.z)<=extent/2;for(const n of p.nodes){if(!point(n)||!Number.isInteger(n.id)||n.id<1||nodes.has(n.id))throw Error('Invalid path node.');nodes.add(n.id);}const edges=new Set(),pairs=new Set();for(const e of p.edges){const pair=[e.a,e.b].sort((a,b)=>a-b).join(':');if(!Number.isInteger(e.id)||e.id<1||edges.has(e.id)||!nodes.has(e.a)||!nodes.has(e.b)||e.a===e.b||pairs.has(pair)||!point(e))throw Error('Invalid path connection.');const a=p.nodes.find(n=>n.id===e.a),b=p.nodes.find(n=>n.id===e.b);if(Math.hypot(a.x-b.x,a.z-b.z)<.05)throw Error('Connected path nodes must be separated.');edges.add(e.id);pairs.add(pair);}if(p.nodes.some(n=>!p.edges.some(e=>e.a===n.id||e.b===n.id)))throw Error('Path nodes need a connection.');return {id:p.id,name:p.name,visible:p.visible,material:p.material,width:p.width,softness:p.softness,seed:p.seed,nodes:p.nodes.map(({id,x,z})=>({id,x,z})),edges:p.edges.map(({id,a,b,x,z})=>({id,a,b,x,z}))};});buildPathIndex(paths,extent);return paths;}
export function pathPoint(a,e,b,t){const u=1-t;return {x:u*u*a.x+2*u*t*e.x+t*t*b.x,z:u*u*a.z+2*u*t*e.z+t*t*b.z};}
export function pathSegments(paths){const out=[];for(const p of paths??[]){if(!p.visible)continue;const nodes=new Map(p.nodes.map(n=>[n.id,n]));for(const e of p.edges){const a=nodes.get(e.a),b=nodes.get(e.b);const length=Math.hypot(e.x-a.x,e.z-a.z)+Math.hypot(b.x-e.x,b.z-e.z),deviation=Math.hypot(e.x-(a.x+b.x)/2,e.z-(a.z+b.z)/2);const steps=Math.min(128,Math.max(1,Math.ceil(Math.sqrt(deviation/Math.max(.025,p.width*.025))),Math.ceil(length/32)));let previous=a;for(let i=1;i<=steps;i++){const q=pathPoint(a,e,b,i/steps);out.push({a:previous,b:q,path:p,edge:e.id});previous=q;if(out.length>PATH_LIMITS.segments)throw Error('Path detail limit reached; simplify connections.');}}}return out;}
export function segmentDistance(x,z,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz||1)));return Math.hypot(x-a.x-t*dx,z-a.z-t*dz);}
export function buildPathIndex(paths,extent){const segments=pathSegments(paths),cells=Array.from({length:4096},()=>[]),cell=v=>Math.max(0,Math.min(63,Math.floor((v/extent+.5)*64)));let references=0;segments.forEach((s,i)=>{const r=s.path.width/2+s.path.softness+3;for(let z=cell(Math.min(s.a.z,s.b.z)-r);z<=cell(Math.max(s.a.z,s.b.z)+r);z++)for(let x=cell(Math.min(s.a.x,s.b.x)-r);x<=cell(Math.max(s.a.x,s.b.x)+r);x++){cells[z*64+x].push(i);if(++references>PATH_LIMITS.references)throw Error('Path spatial index is too dense.');}});return {segments,cells,extent,cell};}
export function hitPath(index,x,z,padding=0){let hit=null,best=Infinity;for(const i of index.cells[index.cell(z)*64+index.cell(x)]){const s=index.segments[i],distance=segmentDistance(x,z,s.a,s.b);if(distance<=s.path.width/2+padding&&distance<best){best=distance;hit=s;}}return hit;}
export function newPath(id,x,z,extent){const half=extent/2,r=Math.min(4,extent/8);x=Math.max(-half+r,Math.min(half-r,x));z=Math.max(-half+r,Math.min(half-r,z));return {id,name:'Path '+id,visible:true,material:1,width:2,softness:.4,seed:42,nodes:[{id:1,x:x-r,z},{id:2,x:x+r,z}],edges:[{id:1,a:1,b:2,x,z}]};}
