import {PATH_TYPES,newPath,buildPathIndex,hitPath,pathPoint,validatePaths} from './path-model.js';
import {terrainHeight} from './map-model.js';
import {surfaceRay} from './scene-camera.js';
export function pathEditor({getMap,commit,preview,view,project,activate,request,frame,toast}){
 const $=id=>document.getElementById(id);let selected=null,node=null,edge=null,extending=false,drag=null;
 const chosen=()=>getMap().paths?.find(p=>p.id===selected);
 const change=fn=>{const m=getMap(),paths=structuredClone(m.paths??[]);fn(paths);commit({...m,paths});refresh();request();};
 function select(id){selected=id;node=null;edge=null;extending=false;activate();refresh();request();}
 function create(x,z){const m=getMap(),p=newPath(Math.max(0,...(m.paths??[]).map(p=>p.id))+1,x,z,m.extent);commit({...m,paths:[...(m.paths??[]),p]});select(p.id);return p;}
 PATH_TYPES.forEach((name,i)=>{const option=document.createElement('option');option.value=i;option.textContent=name;$('pathMaterial').append(option);});
 $('newPath').onclick=()=>{const p=create(Math.max(-getMap().extent/2,Math.min(getMap().extent/2,view.pivot[0])),Math.max(-getMap().extent/2,Math.min(getMap().extent/2,view.pivot[2])));node=p.nodes[1].id;extending=true;refresh();request();toast('Click terrain to extend. Click an existing node to connect. Finish when done.');};
 for(const [id,key]of [['pathName','name'],['pathMaterial','material'],['pathWidth','width'],['pathSoftness','softness'],['pathSeed','seed'],['pathVisible','visible']])$(id).onchange=()=>change(paths=>{const p=paths.find(p=>p.id===selected);if(p)p[key]=key==='name'?$(id).value:key==='visible'?$(id).checked:Number($(id).value);});
 $('extendPath').onclick=()=>{if(!chosen())return;node??=chosen().nodes.at(-1).id;extending=!extending;refresh();request();};
 $('finishPath').onclick=()=>{extending=false;refresh();request();};
 $('deletePath').onclick=()=>{change(paths=>{const i=paths.findIndex(p=>p.id===selected);if(i>=0)paths.splice(i,1);});selected=null;refresh();request();};
 $('framePath').onclick=()=>{const p=chosen();if(!p)return;const x=p.nodes.reduce((s,n)=>s+n.x,0)/p.nodes.length,z=p.nodes.reduce((s,n)=>s+n.z,0)/p.nodes.length;frame([x,terrainHeight(getMap(),x,z),z],Math.max(4,...p.nodes.map(n=>Math.hypot(n.x-x,n.z-z)))+p.width);};
 $('deletePathNode').onclick=()=>{const p=chosen();if(!p||node===null)return;const remain=p.edges.filter(e=>e.a!==node&&e.b!==node);if(!remain.length)return toast('Keep at least one connection, or delete the path.');change(paths=>{const p=paths.find(p=>p.id===selected);p.edges=remain;p.nodes=p.nodes.filter(n=>remain.some(e=>e.a===n.id||e.b===n.id));});node=null;refresh();request();};
 $('splitPathEdge').onclick=()=>{if(!chosen()||edge===null)return;change(paths=>{const p=paths.find(p=>p.id===selected),e=p.edges.find(e=>e.id===edge),a=p.nodes.find(n=>n.id===e.a),b=p.nodes.find(n=>n.id===e.b),q=pathPoint(a,e,b,.5);node=Math.max(...p.nodes.map(n=>n.id))+1;const nextId=Math.max(...p.edges.map(e=>e.id))+1;p.nodes.push({id:node,...q});const oldB=e.b;e.b=node;p.edges.push({id:nextId,a:node,b:oldB,x:(e.x+b.x)/2,z:(e.z+b.z)/2});e.x=(a.x+e.x)/2;e.z=(a.z+e.z)/2;});};
 function refresh(){if(selected&&!chosen())selected=null;const p=chosen();if(!p?.nodes.some(n=>n.id===node))node=null;if(!p?.edges.some(e=>e.id===edge))edge=null;$('pathTransform').disabled=!p;for(const [id,key]of [['pathName','name'],['pathMaterial','material'],['pathWidth','width'],['pathSoftness','softness'],['pathSeed','seed']])$(id).value=p?.[key]??'';$('pathVisible').checked=p?.visible??true;$('extendPath').textContent=extending?'Connecting nodes...':'Extend / connect';$('pathNodeInfo').textContent=p?`${p.nodes.length} nodes / ${p.edges.length} connections${node!==null?' / Node '+node:''}`:'Select a path or create one.';$('deletePathNode').disabled=!p||node===null;$('splitPathEdge').disabled=!p||edge===null;$('finishPath').disabled=!extending;}
 function down(event,screen,world,picked,canDrag=true){const handle=event.target.closest('[data-path-node],[data-path-bend]'),p=chosen();if(handle&&p){if(handle.dataset.pathNode!==undefined){const id=Number(handle.dataset.pathNode);if(extending&&node!==null&&node!==id){change(paths=>{const q=paths.find(p=>p.id===selected);if(q.edges.some(e=>e.a===node&&e.b===id||e.a===id&&e.b===node))return;const a=q.nodes.find(n=>n.id===node),b=q.nodes.find(n=>n.id===id);q.edges.push({id:Math.max(...q.edges.map(e=>e.id))+1,a:node,b:id,x:(a.x+b.x)/2,z:(a.z+b.z)/2});});node=id;refresh();return true;}node=id;edge=null;}else{edge=Number(handle.dataset.pathBend);node=null;extending=false;}if(world.hit)drag={base:structuredClone(getMap()),start:world,node,edge};refresh();request();return true;}
 if(p&&extending&&world.hit){change(paths=>{const q=paths.find(p=>p.id===selected),a=q.nodes.find(n=>n.id===node);if(!a)return;const id=Math.max(...q.nodes.map(n=>n.id))+1;q.nodes.push({id,x:world.x,z:world.z});q.edges.push({id:Math.max(...q.edges.map(e=>e.id))+1,a:node,b:id,x:(a.x+world.x)/2,z:(a.z+world.z)/2});node=id;});return true;}
 if(!world.hit||picked)return false;const hit=hitPath(buildPathIndex(getMap().paths,getMap().extent),world.x,world.z);if(!hit)return false;select(hit.path.id);if(canDrag)drag={base:structuredClone(getMap()),start:world,node:null,edge:null};return true;}
 function move(screen){if(!drag)return false;const world=surfaceRay(view,drag.base,screen);if(!world.hit)return true;const m={...getMap(),paths:structuredClone(drag.base.paths)},p=m.paths.find(p=>p.id===selected),half=m.extent/2,clamp=v=>Math.max(-half,Math.min(half,v));let dx=world.x-drag.start.x,dz=world.z-drag.start.z;if(drag.node!==null){const n=p.nodes.find(n=>n.id===drag.node),x=clamp(n.x+dx),z=clamp(n.z+dz);dx=x-n.x;dz=z-n.z;n.x=x;n.z=z;for(const e of p.edges)if(e.a===n.id||e.b===n.id){e.x=clamp(e.x+dx*.5);e.z=clamp(e.z+dz*.5);}}else if(drag.edge!==null){const e=p.edges.find(e=>e.id===drag.edge);e.x=clamp(e.x+dx);e.z=clamp(e.z+dz);}else{const points=[...p.nodes,...p.edges];dx=Math.max(-half-Math.min(...points.map(n=>n.x)),Math.min(half-Math.max(...points.map(n=>n.x)),dx));dz=Math.max(-half-Math.min(...points.map(n=>n.z)),Math.min(half-Math.max(...points.map(n=>n.z)),dz));for(const n of points){n.x+=dx;n.z+=dz;}}try{validatePaths(m.paths,m.extent);preview(m);}catch(e){toast(e.message);}return true;}
 function end(){if(!drag)return false;drag=null;commit(getMap());refresh();return true;}
 function overlay(){const p=chosen();if(!p)return '';let svg='';const projected=q=>project(q.x,q.z,terrainHeight(getMap(),q.x,q.z)+.035);for(const e of p.edges){const a=p.nodes.find(n=>n.id===e.a),b=p.nodes.find(n=>n.id===e.b),points=[];for(let i=0;i<=32;i++){const q=projected(pathPoint(a,e,b,i/32));if(q.depth>.05)points.push(`${q.x},${q.y}`);}svg+=`<polyline points="${points.join(' ')}" fill="none" stroke="#f9ce8c" stroke-width="2"/>`;const q=projected(e);if(q.depth>.05)svg+=`<rect class="path-handle" data-path-bend="${e.id}" x="${q.x-6}" y="${q.y-6}" width="12" height="12" fill="${edge===e.id?'#ffffff':'#dc9861'}" stroke="#322419"/>`;}
 for(const n of p.nodes){const q=projected(n);if(q.depth>.05)svg+=`<circle class="path-handle" data-path-node="${n.id}" cx="${q.x}" cy="${q.y}" r="7" fill="${node===n.id?'#ffffff':'#f7d8a5'}" stroke="#322419" stroke-width="2"/>`;}return svg;}
 return {create,select,refresh,down,move,end,overlay,getSelected:chosen,isEditing:()=>!!chosen(),cancel(){selected=null;node=null;edge=null;extending=false;drag=null;}};
}
