import {insidePlan,planOutline} from './plan-model.js';import {terrainHeight} from './map-model.js';import {ray,surfaceRay} from './scene-camera.js';import {PRESETS} from './species.js';
export function planEditor({getMap,commit,preview,view,project,mode,request,frame,toast}){const $=id=>document.getElementById(id);let selected=null,draft=null,drag=null,node=null;
const chosen=()=>getMap().plans?.find(p=>p.id===selected);const edit=fn=>{const m=getMap(),plans=structuredClone(m.plans??[]);fn(plans);commit({...m,plans});};
function select(id){node=null;selected=id;mode('plans');refresh();request();}
for(const p of PRESETS.filter(p=>p.id>=61&&p.id<=70)){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('planPreset').append(o);}
for(const type of ['grass','water'])$('draw'+(type==='grass'?'Grass':'Water')+'Plan').onclick=()=>{draft={type,vertices:[]};selected=null;mode('plans');toast('Click corners on the terrain, then Finish outline.');request();};
$('cancelPlan').onclick=()=>{draft=null;request();};$('finishPlan').onclick=()=>{if(!draft||draft.vertices.length<3)return toast('Place at least three corners.');const d=draft;edit(plans=>{selected=Math.max(0,...plans.map(p=>p.id))+1;plans.push({id:selected,name:(d.type==='grass'?'Grass':'Water')+' plan '+selected,type:d.type,vertices:d.vertices,visible:true,seed:42,spacing:2,scale:.4,preset:61,level:terrainHeight(getMap(),d.vertices[0].x,d.vertices[0].z)+.5,kind:'lake'});});if(chosen())draft=null;refresh();request();};
$('planList').onchange=()=>select(Number($('planList').value));
for(const [id,key] of [['planSmooth','smooth'],['planRandomRotation','randomRotation'],['planSeed','seed'],['planName','name'],['planType','type'],['planPreset','preset'],['planSpacing','spacing'],['planScale','scale'],['planLevel','level'],['planKind','kind'],['planVisible','visible']])$(id).onchange=()=>edit(plans=>{const p=plans.find(p=>p.id===selected);if(p)p[key]=['visible','smooth','randomRotation'].includes(key)?$(id).checked:['name','type','kind'].includes(key)?$(id).value:Number($(id).value);});
$('planVertices').onchange=()=>{try{const vertices=$('planVertices').value.trim().split(/\n/).map(line=>{const [x,z]=line.trim().split(/[, ]+/).map(Number);return {x,z};});edit(plans=>{const p=plans.find(p=>p.id===selected);if(p)p.vertices=vertices;});}catch(e){toast(e.message);}};
$('deletePlanNode').onclick=()=>{const p=chosen();if(!p||node===null)return;if(p.vertices.length<=3)return toast('A polygon needs at least three nodes.');edit(plans=>plans.find(p=>p.id===selected).vertices.splice(node,1));node=null;refresh();request();};
$('deletePlan').onclick=()=>edit(plans=>{const i=plans.findIndex(p=>p.id===selected);if(i>=0)plans.splice(i,1);});$('framePlan').onclick=()=>{const p=chosen();if(!p)return;const x=p.vertices.reduce((s,v)=>s+v.x,0)/p.vertices.length,z=p.vertices.reduce((s,v)=>s+v.z,0)/p.vertices.length;frame([x,p.type==='water'?p.level:terrainHeight(getMap(),x,z),z],Math.max(3,...p.vertices.map(v=>Math.hypot(v.x-x,v.z-z))));};
function refresh(){if(selected&&!chosen())selected=null;$('planList').replaceChildren();for(const p of getMap().plans??[]){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('planList').append(o);}$('planList').value=selected??'';const p=chosen();$('planSmooth').checked=p?.smooth??false;$('planRandomRotation').checked=p?.randomRotation??true;$('planSeed').value=p?.seed??42;for(const id of ['planRandomRotation','planSeed'])$(id).parentElement.hidden=p?.type==='water';$('deletePlanNode').disabled=!p||node===null||p.vertices.length<=3;$('planTransform').disabled=!p;$('planHeightLabel').hidden=p?.type!=='water';$('planShoreLabel').hidden=p?.type!=='water';for(const id of ['planPreset','planSpacing','planScale'])$(id).parentElement.hidden=p?.type==='water';for(const [id,key] of [['planName','name'],['planType','type'],['planPreset','preset'],['planSpacing','spacing'],['planScale','scale'],['planLevel','level'],['planKind','kind']])$(id).value=p?.[key]??'';if(p)$('planLevel').value=p.level.toFixed(2);$('planVisible').checked=p?.visible??true;$('planVertices').value=p?p.vertices.map(v=>`${v.x.toFixed(2)}, ${v.z.toFixed(2)}`).join('\n'):'';}
function hitPoint(screen,level){const d=ray(view,screen),t=(level-view.position[1])/d[1];if(!Number.isFinite(t)||t<=0)return null;return {x:view.position[0]+d[0]*t,z:view.position[2]+d[2]*t};}
function dragPoint(screen,plan,map){if(plan.type==='water')return hitPoint(screen,plan.level);const q=surfaceRay(view,map,screen);return q.hit?q:null;}
function down(event,screen,world,picked,renderObjects){const handle=event.target.closest('[data-plan-vertex],[data-plan-edge]');if(handle&&chosen()){const p=chosen(),base=structuredClone(getMap());let vertex=Number(handle.dataset.planVertex);if(handle.dataset.planEdge!==undefined){if(p.vertices.length>=32){toast('Maximum 32 corners.');return true;}const index=Number(handle.dataset.planEdge),q=base.plans.find(p=>p.id===selected),a=q.vertices[index],b=q.vertices[(index+1)%q.vertices.length];vertex=index+1;q.vertices.splice(vertex,0,{x:(a.x+b.x)/2,z:(a.z+b.z)/2});}const start=dragPoint(screen,p,base);if(!start)return true;node=vertex;drag={base,vertex,start};preview(base);refresh();return true;}
if(draft){if(world.hit&&draft.vertices.length<32)draft.vertices.push({x:world.x,z:world.z});request();return true;}
const derived=renderObjects?.find(o=>o.id===picked&&o.planId);let hit=null;if(derived)hit=getMap().plans.find(p=>p.id===derived.planId);if(!picked){let nearest=Infinity;for(const p of getMap().plans??[]){if(!p.visible||p.type!=='water')continue;const q=hitPoint(screen,p.level);if(q&&insidePlan(q.x,q.z,planOutline(p))&&terrainHeight(getMap(),q.x,q.z)<p.level){const d=Math.hypot(q.x-view.position[0],p.level-view.position[1],q.z-view.position[2]);if(d<nearest){nearest=d;hit=p;}}}
if(!hit)for(const p of getMap().water?.planes??[]){if(!p.visible)continue;const q=hitPoint(screen,p.level);if(!q)continue;const a=p.rotation*Math.PI/180,dx=q.x-p.x,dz=q.z-p.z;if(Math.abs(dx*Math.cos(a)+dz*Math.sin(a))>p.width/2||Math.abs(-dx*Math.sin(a)+dz*Math.cos(a))>p.length/2||terrainHeight(getMap(),q.x,q.z)>=p.level)continue;const m=structuredClone(getMap());if(m.plans.length>=16){toast('Maximum 16 plans.');return true;}selected=Math.max(0,...m.plans.map(p=>p.id))+1;const vertices=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([xx,zz])=>({x:p.x+xx*p.width/2*Math.cos(a)-zz*p.length/2*Math.sin(a),z:p.z+xx*p.width/2*Math.sin(a)+zz*p.length/2*Math.cos(a)}));m.water.planes=m.water.planes.filter(q=>q.id!==p.id);m.plans.push({id:selected,name:p.name,type:'water',visible:true,vertices,level:p.level,kind:p.kind,seed:42,spacing:2,scale:.4,preset:61});commit(m);hit=chosen();break;}}
if(!hit&&world.hit&&!picked)hit=(getMap().plans??[]).find(p=>p.visible&&p.type==='grass'&&insidePlan(world.x,world.z,planOutline(p)));if(!hit)return false;select(hit.id);const start=dragPoint(screen,hit,getMap());if(start)drag={base:structuredClone(getMap()),start};return true;}
function move(screen){if(!drag)return false;const original=drag.base.plans.find(p=>p.id===selected),q=dragPoint(screen,original,drag.base);if(!q)return true;const m={...getMap(),plans:structuredClone(drag.base.plans)},p=m.plans.find(p=>p.id===selected),half=m.extent/2;if(drag.vertex!==undefined)p.vertices[drag.vertex]={x:Math.max(-half,Math.min(half,original.vertices[drag.vertex].x+q.x-drag.start.x)),z:Math.max(-half,Math.min(half,original.vertices[drag.vertex].z+q.z-drag.start.z))};else{let dx=q.x-drag.start.x,dz=q.z-drag.start.z;dx=Math.max(-half-Math.min(...p.vertices.map(v=>v.x)),Math.min(half-Math.max(...p.vertices.map(v=>v.x)),dx));dz=Math.max(-half-Math.min(...p.vertices.map(v=>v.z)),Math.min(half-Math.max(...p.vertices.map(v=>v.z)),dz));p.vertices=p.vertices.map(v=>({x:v.x+dx,z:v.z+dz}));}preview(m);return true;}
function end(){if(!drag)return false;drag=null;commit(getMap());return true;}
function overlay(){const p=draft??chosen();if(!p)return '';const v=p.vertices.map(a=>project(a.x,a.z,p.type==='water'&&!draft?p.level:terrainHeight(getMap(),a.x,a.z)+.05));if(v.some(p=>p.depth<.05))return '';const outline=(draft?p.vertices:planOutline(p)).map(a=>project(a.x,a.z,p.type==='water'&&!draft?p.level:terrainHeight(getMap(),a.x,a.z)+.05));let svg=`<${draft?'polyline':'polygon'} points="${outline.map(p=>`${p.x},${p.y}`).join(' ')}" fill="${draft?'none':'#bddd8d15'}" stroke="#e5f7b4" stroke-width="2"/>`;v.forEach((a,i)=>{svg+=`<circle class="plan-handle" data-plan-vertex="${i}" cx="${a.x}" cy="${a.y}" r="7" fill="${i===node?'#ffd779':'#c4e9a0'}" stroke="#18251a" stroke-width="2"/>`;if(!draft){const next=p.vertices[(i+1)%v.length],mx=(p.vertices[i].x+next.x)/2,mz=(p.vertices[i].z+next.z)/2,mid=project(mx,mz,p.type==='water'?p.level:terrainHeight(getMap(),mx,mz)+.05),x=mid.x,y=mid.y;svg+=`<g class="plan-edge" data-plan-edge="${i}"><circle cx="${x}" cy="${y}" r="8" fill="#253637" stroke="#d2eab7"/><text x="${x}" y="${y+4}" text-anchor="middle" fill="white">+</text></g>`;}});return svg;}
function editRectangle(id){const m=structuredClone(getMap()),p=m.water.planes.find(p=>p.id===id);if(!p)return;if(m.plans.length>=16)return toast('Maximum 16 plans.');const a=p.rotation*Math.PI/180;selected=Math.max(0,...m.plans.map(p=>p.id))+1;const vertices=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([xx,zz])=>({x:p.x+xx*p.width/2*Math.cos(a)-zz*p.length/2*Math.sin(a),z:p.z+xx*p.width/2*Math.sin(a)+zz*p.length/2*Math.cos(a)}));m.water.planes=m.water.planes.filter(q=>q.id!==id);m.plans.push({id:selected,name:p.name,type:'water',visible:p.visible,vertices,level:p.level,kind:p.kind,seed:42,spacing:2,scale:.4,preset:61});commit(m);select(selected);}
return {refresh,select,down,move,end,overlay,editRectangle,getSelected:()=>chosen(),isEditing:()=>!!draft||!!chosen(),cancel(){drag=null;draft=null;selected=null;node=null;}};}
