import {terrainHeight} from './map-model.js';
export const add=(a,b)=>a.map((v,i)=>v+b[i]),mul=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0);
export function basis(c){const cp=Math.cos(c.pitch),sp=Math.sin(c.pitch),sy=Math.sin(c.yaw),cy=Math.cos(c.yaw);return {forward:[sy*cp,sp,cy*cp],right:[cy,0,-sy],up:[-sy*sp,cp,-cy*sp]};}
export function createCamera(){return {position:[18,16,-22],yaw:-.65,pitch:-.45,pivot:[0,0,0],distance:30,speed:10,fov:60,aspect:4/3,grid:true};}
export function projectPoint(c,p,w=1024,h=768){const b=basis(c),r=p.map((v,i)=>v-c.position[i]),z=dot(r,b.forward),f=1/Math.tan(c.fov*Math.PI/360);return {x:w*.5+dot(r,b.right)*f/c.aspect/Math.max(.001,z)*w*.5,y:h*.5-dot(r,b.up)*f/Math.max(.001,z)*h*.5,depth:z};}
// Reuse camera trigonometry while projecting many bounds in one frame.
// Arithmetic order matches projectPoint so culling stays pixel-identical.
export function cameraProjector(c,w=1024,h=768){const b=basis(c),f=1/Math.tan(c.fov*Math.PI/360),cx=c.position[0],cy=c.position[1],cz=c.position[2];return (x,y,z)=>{const rx=x-cx,ry=y-cy,rz=z-cz,depth=0+rx*b.forward[0]+ry*b.forward[1]+rz*b.forward[2],right=0+rx*b.right[0]+ry*b.right[1]+rz*b.right[2],up=0+rx*b.up[0]+ry*b.up[1]+rz*b.up[2];return {x:w*.5+right*f/c.aspect/Math.max(.001,depth)*w*.5,y:h*.5-up*f/Math.max(.001,depth)*h*.5,depth};};}
export function ray(c,p,w=1024,h=768){const b=basis(c),t=Math.tan(c.fov*Math.PI/360);const v=add(b.forward,add(mul(b.right,(p.x/w*2-1)*t*c.aspect),mul(b.up,(1-p.y/h*2)*t)));return mul(v,1/Math.hypot(...v));}
export function frameCamera(c,p,radius){c.pivot=[...p];c.distance=Math.max(3,radius/Math.tan(c.fov*Math.PI/360)*1.25);c.position=add(c.pivot,mul(basis(c).forward,-c.distance));}
export function orbitCamera(c,dx,dy){c.yaw-=dx*.005;c.pitch=Math.max(-1.53,Math.min(1.53,c.pitch+dy*.005));c.position=add(c.pivot,mul(basis(c).forward,-c.distance));}
export function lookCamera(c,dx,dy){c.yaw+=dx*.004;c.pitch=Math.max(-1.53,Math.min(1.53,c.pitch-dy*.004));c.pivot=add(c.position,mul(basis(c).forward,c.distance));}
export function panCamera(c,dx,dy,height){const b=basis(c),scale=2*c.distance*Math.tan(c.fov*Math.PI/360)/height;const d=add(mul(b.right,-dx*scale),mul(b.up,dy*scale));c.position=add(c.position,d);c.pivot=add(c.pivot,d);}
export function dollyCamera(c,delta){const next=Math.max(.5,Math.min(200000,c.distance*Math.exp(delta*.001)));c.position=add(c.position,mul(basis(c).forward,c.distance-next));c.distance=next;}
export function flyCamera(c,keys,dt){const b=basis(c);let v=add(mul(b.forward,(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)),mul(b.right,(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)));v[1]+=(keys.has('KeyE')?1:0)-(keys.has('KeyQ')?1:0);const len=Math.hypot(...v);if(!len)return false;v=mul(v,c.speed*dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?4:1)/len);c.position=add(c.position,v);c.pivot=add(c.pivot,v);return true;}
export function surfaceRay(c,map,p){const d=ray(c,p);let t=.05,prior=t;for(let step=0;step<320;step++){const q=add(c.position,mul(d,t));if(Math.abs(q[0])<=map.extent/2&&Math.abs(q[2])<=map.extent/2&&q[1]<=terrainHeight(map,q[0],q[2])){let lo=prior,hi=t;for(let k=0;k<12;k++){const m=(lo+hi)/2,a=add(c.position,mul(d,m));if(a[1]>terrainHeight(map,a[0],a[2]))lo=m;else hi=m;}const a=add(c.position,mul(d,(lo+hi)/2));return {x:a[0],z:a[2],hit:true};}prior=t;t+=Math.max(.25,t*.035);if(t>map.extent*3+10000)break;}const t0=Math.abs(d[1])>.0001?-c.position[1]/d[1]:c.distance;const q=add(c.position,mul(d,Math.max(0,t0)));return {x:q[0],z:q[2],hit:false};}
