__device__ float polygon_distance(const float4* points,int index,int count,float x,float z){int inside=0;float closest=1000000.0f;for(int i=0;i<count;i++){int j=i+1;if(j==count)j=0;float4 a=points[index*128+i];float4 b=points[index*128+j];if((a.y>z)!=(b.y>z)){float hit=(b.x-a.x)*(z-a.y)/(b.y-a.y)+a.x;if(x<hit)inside=1-inside;}float dx=b.x-a.x;float dz=b.y-a.y;float t=fminf(1.0f,fmaxf(0.0f,((x-a.x)*dx+(z-a.y)*dz)/fmaxf(.00001f,dx*dx+dz*dz)));float ex=x-a.x-dx*t;float ez=z-a.y-dz*t;closest=fminf(closest,sqrtf(ex*ex+ez*ez));}if(inside!=0)return 0.0f;return closest;}
// Lightweight adaptation of ClearWater's dielectric Fresnel / wind-driven normal approach.
// See docs/water.md and vendor/LICENSE.ClearWater for FFT and optics provenance.
__device__ float water_fresnel(float ci){ci=fminf(1.0f,fmaxf(0.0f,ci));float ct=sqrtf(1.0f-(1.0f-ci*ci)/(1.3335f*1.3335f));float rs=(ci-1.3335f*ct)/(ci+1.3335f*ct);float rp=(1.3335f*ci-ct)/(1.3335f*ci+ct);return .5f*(rs*rs+rp*rp);}
// Closest water boundary, with separate ocean / lake / pond material identity.
__device__ float4 water_context(const float4* waters,const float4* waterPoints,int waterCount,float x,float z,float ground){float best=1000000.0f;float4 result=make_float4(0.0f,1000000.0f,0.0f,0.0f);for(int j=0;j<waterCount;j++){float4 a=waters[j*2];float4 b=waters[j*2+1];float dx=x-a.x;float dz=z-a.y;float u=dx*cosf(b.y)+dz*sinf(b.y);float v=-dx*sinf(b.y)+dz*cosf(b.y);float d=0.0f;if(a.z>0.0f){float ex=fmaxf(0.0f,fabsf(u)-a.z);float ez=fmaxf(0.0f,fabsf(v)-a.w);d=sqrtf(ex*ex+ez*ez);}if(b.w>=3.0f)d=polygon_distance(waterPoints,j,(int)b.w,x,z);float score=d+fabsf(ground-b.x)*3.0f;if(d==0.0f&&ground<b.x)score=-10000.0f-b.x;if(score<best){best=score;result=make_float4(b.x,d,b.z,1.0f);}}return result;}
__global__ void scene_water(const float4* waves,const float4* reflections,const unsigned int* scenePixels,const unsigned int* sceneDepth,unsigned int* waterMask,const float4* waters,const float4* waterPoints,const float* base,const float* tiles,const int* table,unsigned int* depth,unsigned int* pixels,unsigned int* picks,int waterCount,int w,int h,float cx,float cy,float cz,float yaw,float pitch,float aspect,float tangent,float extent,float time,float windDirection,float windSpeed,float rain,float clouds,float waveStrength,int reflectionEnabled,float lx,float ly,float lz){
unsigned int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=(unsigned int)(w*h))return;
float sx=(((float)(i%(unsigned int)w)+.5f)/(float)w*2.0f-1.0f)*tangent*aspect;float sy=(1.0f-((float)(i/(unsigned int)w)+.5f)/(float)h*2.0f)*tangent;float cp=cosf(pitch);float sp=sinf(pitch);float ca=cosf(yaw);float sa=sinf(yaw);float dx=sa*cp+ca*sx-sa*sp*sy;float dy=sp+cp*sy;float dz=ca*cp-sa*sx-ca*sp*sy;float dl=sqrtf(dx*dx+dy*dy+dz*dz);dx/=dl;dy/=dl;dz/=dl;if(dy>=-.00001f)return;
float closest=10000000.0f;int found=-1;for(int j=0;j<waterCount;j++){float4 a=waters[j*2];float4 b=waters[j*2+1];float t=(b.x-cy)/dy;if(t<=.05f||t>=closest)continue;float x=cx+dx*t-a.x;float z=cz+dz*t-a.y;if(a.z>0.0f&&(fabsf(x*cosf(b.y)+z*sinf(b.y))>a.z||fabsf(-x*sinf(b.y)+z*cosf(b.y))>a.w))continue;if(b.w>=3.0f&&polygon_distance(waterPoints,j,(int)b.w,cx+dx*t,cz+dz*t)>0.0f)continue;closest=t;found=j;}if(found<0)return;
float forward=dx*sa*cp+dy*sp+dz*ca*cp;unsigned int key=(unsigned int)(closest*forward*1000.0f);if(key>=depth[i])return;float x=cx+dx*closest;float z=cz+dz*closest;float4 info=waters[found*2+1];float edgeX=fminf(extent*.5f,fmaxf(-extent*.5f,x));float edgeZ=fminf(extent*.5f,fmaxf(-extent*.5f,z));float outside=sqrtf((x-edgeX)*(x-edgeX)+(z-edgeZ)*(z-edgeZ));float bed=terrain_world(base,tiles,table,edgeX,edgeZ,extent)-outside*.35f;if(outside>0.0f)bed=fminf(bed,info.x-.08f-outside*.35f);float waterDepth=info.x-bed;if(waterDepth<=0.0f)return;
float4 flow=waterPoints[found*128];float flowAngle=flow.z*.0174532925f;float flowX=cosf(flowAngle)*time*flow.w;float flowZ=sinf(flowAngle)*time*flow.w;x-=flowX;z-=flowZ;float angle=windDirection*.0174532925f;float u=x*cosf(angle)+z*sinf(angle);float v=-x*sinf(angle)+z*cosf(angle);float fade=1.0f/(1.0f+closest*.015f);float drift=time*(.25f+windSpeed*.06f);float pixelFootprint=closest*tangent*2.0f/(float)h/fmaxf(.08f,-dy);float rippleFilter=1.0f/(1.0f+pixelFootprint*pixelFootprint*4.0f);
float4 spectral=water_field(waves,x,z,angle,pixelFootprint);float depthDamping=.35f+.65f*fminf(1.0f,waterDepth/1.8f);float nx=-spectral.y*waveStrength*depthDamping;float nz=-spectral.z*waveStrength*depthDamping;
float nl=sqrtf(nx*nx+1.0f+nz*nz);nx/=nl;nz/=nl;float ny=1.0f/nl;float nv=fmaxf(.02f,-dx*nx-dy*ny-dz*nz);float fresnel=water_fresnel(nv);float light=.55f+.45f*fmaxf(0.0f,nx*lx+ny*ly+nz*lz);float deep=1.0f-expf(-waterDepth*.23f);float r=.10f-deep*.065f;float g=.56f-deep*.30f;float b=.56f-deep*.16f;if(info.z<.5f){r+=.035f;g-=.045f;b-=.08f;}
float band=1.0f+fminf(.12f,fmaxf(-.12f,spectral.x*.16f));r*=light*band;g*=light*band;b*=light*band;float bodyR=r;float bodyG=g;float bodyB=b;
float rd=dx*nx+dy*ny+dz*nz;float rx=dx-2.0f*rd*nx;float ry=fabsf(dy-2.0f*rd*ny);float rz=dz-2.0f*rd*nz;float skyR=.34f-.18f*ry;float skyG=.63f-.16f*ry;float skyB=.82f-.10f*ry;
float ct=(600.0f-info.x)/fmaxf(.04f,ry);float density=cloud_density(x+rx*ct,z+rz*ct,time,windSpeed,windDirection);float cloud=fminf(1.0f,fmaxf(0.0f,(density-(.83f-clouds*.6f))/.055f));float cloudShade=.84f-rain*.38f;skyR=skyR*(1.0f-cloud)+cloudShade*cloud;skyG=skyG*(1.0f-cloud)+(cloudShade+.025f)*cloud;skyB=skyB*(1.0f-cloud)+(cloudShade+.05f)*cloud;
int rw=(w+1)/2;int rh=(h+1)/2;float fx=((float)(i%(unsigned int)w)+.5f)*.5f-.5f;float fy=((float)(i/(unsigned int)w)+.5f)*.5f-.5f;int ix=(int)floorf(fx);int iy=(int)floorf(fy);float fu=fx-floorf(fx);float fv=fy-floorf(fy);float rr=0.0f;float rg=0.0f;float rb=0.0f;float confidence=0.0f;
if(reflectionEnabled!=0){for(int yy=0;yy<2;yy++)for(int xx=0;xx<2;xx++){float4 sample=reflections[min(rh-1,max(0,iy+yy))*rw+min(rw-1,max(0,ix+xx))];float weight=(xx==0?1.0f-fu:fu)*(yy==0?1.0f-fv:fv)*sample.w;rr+=sample.x*weight;rg+=sample.y*weight;rb+=sample.z*weight;confidence+=weight;}}
skyR=skyR*(1.0f-confidence)+rr;skyG=skyG*(1.0f-confidence)+rg;skyB=skyB*(1.0f-confidence)+rb;float reflection=fminf(.90f,fresnel);r=r*(1.0f-reflection)+skyR*reflection;g=g*(1.0f-reflection)+skyG*reflection;b=b*(1.0f-reflection)+skyB*reflection;
float hx=lx-dx;float hy=ly-dy;float hz=lz-dz;float hl=sqrtf(hx*hx+hy*hy+hz*hz);float highlight=powf(fmaxf(0.0f,(nx*hx+ny*hy+nz*hz)/fmaxf(.01f,hl)),64.0f)*.65f/(1.0f+pixelFootprint*.1f);
// A narrow broken wash at the shore, not thresholded stripes across the shallows.
float wash=noise3(x*1.1f-time*.09f,3.0f,z*1.1f+time*.06f);
float surge=.5f+.5f*sinf(waterDepth*10.0f-time*1.7f+spectral.x*2.0f+wash*2.0f);float foamWidth=.12f+.13f*wash+.06f*surge;float foam=expf(-waterDepth/fmaxf(.03f,foamWidth))*(.20f+.36f*wash+.15f*surge);
foam*=fminf(1.0f,waterDepth/.025f);float footprint=closest*tangent*2.0f/(float)h/fmaxf(.08f,-dy);float strokeFade=1.0f/(1.0f+footprint*footprint*16.0f);float fleck=noise3(u*.8f-drift*.3f,8.0f,v*1.8f);float strokes=fmaxf(0.0f,fleck-.65f)*.10f*fade*strokeFade*(1.0f+rain);float skyDim=1.0f-rain*.25f;r=(r+highlight+strokes)*skyDim;g=(g+highlight+strokes)*skyDim;b=(b+highlight+strokes)*skyDim;r=r*(1.0f-foam)+.78f*foam;g=g*(1.0f-foam)+.91f*foam;b=b*(1.0f-foam)+.85f*foam;
// Beer-Lambert attenuation along the viewing ray, rather than a fixed opacity.
// Keep surface reflection and foam visible even in transparent shallows.
float pathLength=waterDepth/fmaxf(.08f,-dy);if(depth[i]!=4294967295u)pathLength=fmaxf(0.0f,(float)depth[i]/(1000.0f*fmaxf(.001f,forward))-closest);
float absorption=info.z<.5f?.55f:info.z<1.5f?.32f:.22f;
float transmission=expf(-pathLength*absorption)*(1.0f-reflection)*(1.0f-foam);if(sceneDepth[i]==4294967295u)transmission=0.0f;
// Refraction reads an immutable opaque-scene snapshot, never neighbouring water writes.
int refracted=(int)i;float bend=fminf(7.0f,waterDepth*2.0f)*rippleFilter;int qx=min(w-1,max(0,(int)(i%(unsigned int)w)+(int)(nx*bend*8.0f)));int qy=min(h-1,max(0,(int)(i/(unsigned int)w)+(int)(nz*bend*8.0f)));int candidate=qy*w+qx;if(sceneDepth[candidate]>key&&sceneDepth[candidate]!=4294967295u)refracted=candidate;unsigned int old=scenePixels[refracted];
// Slope divergence approximates focusing. Restrict caustics to sunlit shallow beds.
float focusing=fminf(2.2f,fmaxf(.6f,1.0f/(fmaxf(.45f,1.0f+spectral.w*waterDepth*3.6f))));float caustic=(focusing-1.0f)*1.1f*expf(-waterDepth*.35f)*fminf(1.0f,waterDepth*3.0f)*fmaxf(0.0f,ly)*(1.0f-rain*.85f)*rippleFilter;
float underR=(float)(old&255u)/255.0f;float underG=(float)((old>>8)&255u)/255.0f;float underB=(float)((old>>16)&255u)/255.0f;underR*=1.0f+caustic;underG*=1.0f+caustic;underB*=1.0f+caustic*.8f;
r=r-bodyR*skyDim*transmission+underR*transmission;g=g-bodyG*skyDim*transmission+underG*transmission;b=b-bodyB*skyDim*transmission+underB*transmission;

waterMask[i]=1u;depth[i]=key;picks[i]=0u;pixels[i]=(unsigned int)(fminf(1.0f,r)*255.0f)|((unsigned int)(fminf(1.0f,g)*255.0f)<<8)|((unsigned int)(fminf(1.0f,b)*255.0f)<<16)|4278190080u;
}

// Half-resolution SSR: bounded sixteen steps and three refinements, opaque scene only.
__global__ void water_reflections(const float4* waves,const float4* waters,const float4* waterPoints,const unsigned int* depth,const unsigned int* pixels,float4* reflections,int waterCount,int w,int h,float cx,float cy,float cz,float yaw,float pitch,float aspect,float tangent,float time,float windDirection,float waveStrength){
 int i=(int)(blockIdx.x*blockDim.x+threadIdx.x);int rw=(w+1)/2;int rh=(h+1)/2;if(i>=rw*rh)return;reflections[i]=make_float4(0.0f,0.0f,0.0f,0.0f);float px=fminf((float)w-.5f,(float)(i%rw)*2.0f+1.0f);float py=fminf((float)h-.5f,(float)(i/rw)*2.0f+1.0f);float sx=(px/(float)w*2.0f-1.0f)*tangent*aspect;float sy=(1.0f-py/(float)h*2.0f)*tangent;float cp=cosf(pitch);float sp=sinf(pitch);float ca=cosf(yaw);float sa=sinf(yaw);float dx=sa*cp+ca*sx-sa*sp*sy;float dy=sp+cp*sy;float dz=ca*cp-sa*sx-ca*sp*sy;float dl=sqrtf(dx*dx+dy*dy+dz*dz);dx/=dl;dy/=dl;dz/=dl;if(dy>=-.001f)return;
 float closest=10000000.0f;int found=-1;for(int j=0;j<waterCount;j++){float4 a=waters[j*2];float4 b=waters[j*2+1];float t=(b.x-cy)/dy;if(t<=.05f||t>=closest)continue;float x=cx+dx*t-a.x;float z=cz+dz*t-a.y;if(a.z>0.0f&&(fabsf(x*cosf(b.y)+z*sinf(b.y))>a.z||fabsf(-x*sinf(b.y)+z*cosf(b.y))>a.w))continue;if(b.w>=3.0f&&polygon_distance(waterPoints,j,(int)b.w,cx+dx*t,cz+dz*t)>0.0f)continue;closest=t;found=j;}if(found<0)return;
 int origin=min(h-1,(int)py)*w+min(w-1,(int)px);float forward=dx*sa*cp+dy*sp+dz*ca*cp;float scene=(float)depth[origin]*.001f;if(closest*forward>=scene)return;
 float4 flow=waterPoints[found*128];float fa=flow.z*.0174532925f;float wx=cx+dx*closest;float wz=cz+dz*closest;float footprint=closest*tangent*2.0f/(float)h/fmaxf(.08f,-dy);float4 wave=water_field(waves,wx-cosf(fa)*time*flow.w,wz-sinf(fa)*time*flow.w,windDirection*.0174532925f,footprint);float waterDepth=fmaxf(0.0f,(scene/fmaxf(.001f,forward)-closest)*(-dy));float damping=.35f+.65f*fminf(1.0f,waterDepth/1.8f);float nx=-wave.y*waveStrength*damping;float nz=-wave.z*waveStrength*damping;float nl=sqrtf(nx*nx+1.0f+nz*nz);nx/=nl;nz/=nl;float ny=1.0f/nl;float dot=dx*nx+dy*ny+dz*nz;float rx=dx-2.0f*dot*nx;float ry=dy-2.0f*dot*ny;float rz=dz-2.0f*dot*nz;if(ry<=.01f)return;
 float length=.6f;float previous=0.0f;float stride=.8f;float level=waters[found*2+1].x;int hit=-1;float weight=0.0f;
 for(int step=0;step<16;step++){float x=dx*closest+rx*length;float y=dy*closest+ry*length+.08f;float z=dz*closest+rz*length;float d=x*sa*cp+y*sp+z*ca*cp;if(d<.05f)break;float u=.5f+(x*ca-z*sa)/(d*tangent*aspect)*.5f;float v=.5f-(-x*sa*sp+y*cp-z*ca*sp)/(d*tangent)*.5f;if(u<=0.0f||v<=0.0f||u>=1.0f||v>=1.0f)break;int at=min(h-1,(int)(v*(float)h))*w+min(w-1,(int)(u*(float)w));float delta=d-(float)depth[at]*.001f;
 if(depth[at]!=4294967295u&&delta>0.0f&&delta<fmaxf(.4f,stride*1.7f)&&cy+y>level+.1f){float lo=previous;float hi=length;for(int refine=0;refine<3;refine++){float mid=(lo+hi)*.5f;float qx=dx*closest+rx*mid;float qy=dy*closest+ry*mid+.08f;float qz=dz*closest+rz*mid;float qd=qx*sa*cp+qy*sp+qz*ca*cp;float qu=.5f+(qx*ca-qz*sa)/(qd*tangent*aspect)*.5f;float qv=.5f-(-qx*sa*sp+qy*cp-qz*ca*sp)/(qd*tangent)*.5f;int q=min(h-1,max(0,(int)(qv*(float)h)))*w+min(w-1,max(0,(int)(qu*(float)w)));if(qd>(float)depth[q]*.001f){hi=mid;at=q;u=qu;v=qv;}else lo=mid;}hit=at;weight=fminf(1.0f,fminf(fminf(u,1.0f-u),fminf(v,1.0f-v))*12.0f);weight*=1.0f-(float)step/24.0f;break;}
 previous=length;length+=stride;stride*=1.45f;}
 if(hit>=0){unsigned int colour=pixels[hit];reflections[i]=make_float4((float)(colour&255u)/255.0f,(float)((colour>>8)&255u)/255.0f,(float)((colour>>16)&255u)/255.0f,weight);}
}

// Underwater view: depth absorption, a bright surface window and restrained distortion.
__global__ void scene_underwater(const unsigned int* source,const unsigned int* depth,unsigned int* target,int w,int h,float cy,float level,float yaw,float pitch,float tangent,float aspect,float time,float day){
 unsigned int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=(unsigned int)(w*h))return;int x=(int)(i%(unsigned int)w);int y=(int)(i/(unsigned int)w);float sx=(((float)x+.5f)/(float)w*2.0f-1.0f)*tangent*aspect;float sy=(1.0f-((float)y+.5f)/(float)h*2.0f)*tangent;float rayY=sinf(pitch)+cosf(pitch)*sy;float rayLength=sqrtf(1.0f+sx*sx+sy*sy);float distance=depth[i]==4294967295u?120.0f:(float)depth[i]*.001f*rayLength;float toSurface=120.0f;if(rayY>.0001f)toSurface=fmaxf(0.0f,(level-cy)/rayY)*rayLength;distance=fminf(distance,toSurface);float immersion=fminf(1.0f,fmaxf(0.0f,(level-cy)*3.0f));float fog=1.0f-expf(-distance*.055f);float illumination=.18f+.82f*day;int ox=(int)(sinf((float)y*.035f+time*1.4f)*1.5f*immersion);int oy=(int)(sinf((float)x*.026f-time)*immersion);unsigned int c=source[min(h-1,max(0,y+oy))*w+min(w-1,max(0,x+ox))];float r=(float)(c&255u)/255.0f;float g=(float)((c>>8)&255u)/255.0f;float b=(float)((c>>16)&255u)/255.0f;
 r=r*expf(-distance*.07f)*(1.0f-fog)+.025f*illumination*fog;g=g*(1.0f-fog)+.29f*illumination*fog;b=b*(1.0f-fog)+.34f*illumination*fog;
 if(toSurface<120.0f&&toSurface<=distance+.01f){float window=fmaxf(0.0f,rayY/rayLength);float ripple=.5f+.5f*sinf((float)x*.028f+time*1.5f+sinf((float)y*.037f));float aperture=fminf(1.0f,fmaxf(0.0f,(window-.62f)/.14f));float surface=.85f+.15f*ripple;r=r*aperture+.035f*surface*illumination*(1.0f-aperture);g=g*aperture+.28f*surface*illumination*(1.0f-aperture);b=b*aperture+.33f*surface*illumination*(1.0f-aperture);float tint=.03f+.04f*ripple;r+=tint*window*illumination;g+=tint*window*illumination;b+=tint*window*illumination;}
 target[i]=(unsigned int)(fminf(1.0f,r)*255.0f)|((unsigned int)(fminf(1.0f,g)*255.0f)<<8)|((unsigned int)(fminf(1.0f,b)*255.0f)<<16)|4278190080u;
}
