import {defaultWater,MAX_WATER_PLANES} from './water-model.js';
import {terrainHeight} from './map-model.js';
export function waterEditor({getMap,commit,preview,view,frame,request,toast,editOutline}){const $=id=>document.getElementById(id);let selected=null,placing=false;const chosen=()=>getMap().water?.planes.find(p=>p.id===selected);const edit=fn=>{const map=getMap();const water=structuredClone(map.water??defaultWater());fn(water);commit({...map,water});};
function add(x,z){if((getMap().water?.planes.length??0)>=MAX_WATER_PLANES)return toast('Maximum 32 water planes.');edit(w=>{selected=Math.max(0,...w.planes.map(p=>p.id))+1;w.planes.push({id:selected,name:'Water '+selected,kind:'lake',x,z,level:terrainHeight(getMap(),x,z)+.5,width:24,length:24,rotation:0,visible:true});});}
$('addWater').onclick=()=>add(Math.max(-getMap().extent/2,Math.min(getMap().extent/2,view.pivot[0])),Math.max(-getMap().extent/2,Math.min(getMap().extent/2,view.pivot[2])));
$('placeWater').onclick=()=>{placing=true;toast('Click the terrain to place a water plane, then adjust its size and height.');};
$('waterList').onchange=()=>{selected=Number($('waterList').value);refresh();};
$('oceanEnabled').onchange=()=>edit(w=>w.ocean.enabled=$('oceanEnabled').checked);$('oceanLevel').onchange=()=>edit(w=>w.ocean.level=Number($('oceanLevel').value));
for(const [id,key] of [['waterName','name'],['waterKind','kind'],['waterX','x'],['waterZ','z'],['waterLevel','level'],['waterWidth','width'],['waterLength','length'],['waterRotation','rotation'],['waterVisible','visible']])$(id).onchange=()=>edit(w=>{const p=w.planes.find(p=>p.id===selected);if(p)p[key]=key==='visible'?$(id).checked:['name','kind'].includes(key)?$(id).value:Number($(id).value);});
$('editWaterOutline').onclick=()=>{if(selected)editOutline(selected);};$('removeWater').onclick=()=>edit(w=>w.planes=w.planes.filter(p=>p.id!==selected));$('frameWater').onclick=()=>{const p=chosen();if(p)frame([p.x,p.level,p.z],Math.max(p.width,p.length)*.65);};
for(const [id,key] of [['waterWindDirection','windDirection'],['waterWindSpeed','windSpeed'],['waterRain','rain']]){const next=()=>{const map=getMap(),water=map.water??defaultWater();return {...map,water:{...water,weather:{...water.weather,[key]:Number($(id).value)}}};};$(id).oninput=()=>preview(next());$(id).onchange=()=>commit(next());}
$('animateWater').onchange=()=>{view.animateWater=$('animateWater').checked;request();};
function refresh(){const w=getMap().water??defaultWater();if(!w.planes.some(p=>p.id===selected))selected=w.planes[0]?.id??null;$('oceanEnabled').checked=w.ocean.enabled;$('oceanLevel').value=w.ocean.level;$('waterList').replaceChildren();for(const p of w.planes){const option=document.createElement('option');option.value=p.id;option.textContent=p.name;$('waterList').append(option);}$('waterList').value=selected??'';const p=chosen();$('waterTransform').disabled=!p;for(const [id,key] of [['waterName','name'],['waterKind','kind'],['waterX','x'],['waterZ','z'],['waterLevel','level'],['waterWidth','width'],['waterLength','length'],['waterRotation','rotation']])$(id).value=p?.[key]??'';$('waterVisible').checked=p?.visible??true;for(const [id,key] of [['waterWindDirection','windDirection'],['waterWindSpeed','windSpeed'],['waterRain','rain']])$(id).value=w.weather[key];}
return {refresh,place(world){if(!placing)return false;if(world.hit){add(world.x,world.z);placing=false;}return true;}};}
