__device__ float polygon_distance(const float4* points,int index,int count,float x,float z){int inside=0;float closest=1000000.0f;for(int i=0;i<count;i++){int j=i+1;if(j==count)j=0;float4 a=points[index*128+i];float4 b=points[index*128+j];if((a.y>z)!=(b.y>z)){float hit=(b.x-a.x)*(z-a.y)/(b.y-a.y)+a.x;if(x<hit)inside=1-inside;}float dx=b.x-a.x;float dz=b.y-a.y;float t=fminf(1.0f,fmaxf(0.0f,((x-a.x)*dx+(z-a.y)*dz)/fmaxf(.00001f,dx*dx+dz*dz)));float ex=x-a.x-dx*t;float ez=z-a.y-dz*t;closest=fminf(closest,sqrtf(ex*ex+ez*ez));}if(inside!=0)return 0.0f;return closest;}
// Lightweight adaptation of ClearWater's dielectric Fresnel / wind-driven normal approach.
// See docs/water.md and vendor/LICENSE.ClearWater. No FFT or simulation buffers.
__device__ float water_fresnel(float ci){ci=fminf(1.0f,fmaxf(0.0f,ci));float ct=sqrtf(1.0f-(1.0f-ci*ci)/(1.3335f*1.3335f));float rs=(ci-1.3335f*ct)/(ci+1.3335f*ct);float rp=(1.3335f*ci-ct)/(1.3335f*ci+ct);return .5f*(rs*rs+rp*rp);}
// Closest water boundary, with separate ocean / lake / pond material identity.
__device__ float4 water_context(const float4* waters,const float4* waterPoints,int waterCount,float x,float z,float ground){float best=1000000.0f;float4 result=make_float4(0.0f,1000000.0f,0.0f,0.0f);for(int j=0;j<waterCount;j++){float4 a=waters[j*2];float4 b=waters[j*2+1];float dx=x-a.x;float dz=z-a.y;float u=dx*cosf(b.y)+dz*sinf(b.y);float v=-dx*sinf(b.y)+dz*cosf(b.y);float d=0.0f;if(a.z>0.0f){float ex=fmaxf(0.0f,fabsf(u)-a.z);float ez=fmaxf(0.0f,fabsf(v)-a.w);d=sqrtf(ex*ex+ez*ez);}if(b.w>=3.0f)d=polygon_distance(waterPoints,j,(int)b.w,x,z);float score=d+fabsf(ground-b.x)*3.0f;if(d==0.0f&&ground<b.x)score=-10000.0f-b.x;if(score<best){best=score;result=make_float4(b.x,d,b.z,1.0f);}}return result;}
__global__ void scene_water(const float4* waters,const float4* waterPoints,const float* base,const float* tiles,const int* table,unsigned int* depth,unsigned int* pixels,unsigned int* picks,int waterCount,int w,int h,float cx,float cy,float cz,float yaw,float pitch,float aspect,float tangent,float extent,float time,float windDirection,float windSpeed,float rain,float lx,float ly,float lz){
unsigned int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=(unsigned int)(w*h))return;
float sx=(((float)(i%(unsigned int)w)+.5f)/(float)w*2.0f-1.0f)*tangent*aspect;float sy=(1.0f-((float)(i/(unsigned int)w)+.5f)/(float)h*2.0f)*tangent;float cp=cosf(pitch);float sp=sinf(pitch);float ca=cosf(yaw);float sa=sinf(yaw);float dx=sa*cp+ca*sx-sa*sp*sy;float dy=sp+cp*sy;float dz=ca*cp-sa*sx-ca*sp*sy;float dl=sqrtf(dx*dx+dy*dy+dz*dz);dx/=dl;dy/=dl;dz/=dl;if(dy>=-.00001f)return;
float closest=10000000.0f;int found=-1;for(int j=0;j<waterCount;j++){float4 a=waters[j*2];float4 b=waters[j*2+1];float t=(b.x-cy)/dy;if(t<=.05f||t>=closest)continue;float x=cx+dx*t-a.x;float z=cz+dz*t-a.y;if(a.z>0.0f&&(fabsf(x*cosf(b.y)+z*sinf(b.y))>a.z||fabsf(-x*sinf(b.y)+z*cosf(b.y))>a.w))continue;if(b.w>=3.0f&&polygon_distance(waterPoints,j,(int)b.w,cx+dx*t,cz+dz*t)>0.0f)continue;closest=t;found=j;}if(found<0)return;
float forward=dx*sa*cp+dy*sp+dz*ca*cp;unsigned int key=(unsigned int)(closest*forward*1000.0f);if(key>=depth[i])return;float x=cx+dx*closest;float z=cz+dz*closest;float4 info=waters[found*2+1];float edgeX=fminf(extent*.5f,fmaxf(-extent*.5f,x));float edgeZ=fminf(extent*.5f,fmaxf(-extent*.5f,z));float outside=sqrtf((x-edgeX)*(x-edgeX)+(z-edgeZ)*(z-edgeZ));float bed=terrain_world(base,tiles,table,edgeX,edgeZ,extent)-outside*.35f;float waterDepth=info.x-bed;if(waterDepth<=0.0f)return;
float angle=windDirection*.0174532925f;float u=x*cosf(angle)+z*sinf(angle);float v=-x*sinf(angle)+z*cosf(angle);float amplitude=(.025f+windSpeed*.006f)*(info.z<.5f?.55f:1.0f);float fade=1.0f/(1.0f+closest*.015f);float drift=time*(.25f+windSpeed*.06f);float patch=noise3(u*.19f-drift*.15f,4.0f,v*.23f);float wave=cosf(u*.72f+v*.23f-drift+patch*4.0f)*.7f+cosf(u*1.7f-v*.9f-time*1.3f+patch*2.0f)*.3f;float cross=cosf(v*1.25f+u*.31f-time*.8f+patch*3.0f)*.4f;float nx=-(wave*cosf(angle)-cross*sinf(angle))*amplitude*fade;float nz=-(wave*sinf(angle)+cross*cosf(angle))*amplitude*fade;float nl=sqrtf(nx*nx+1.0f+nz*nz);nx/=nl;nz/=nl;float ny=1.0f/nl;float nv=fmaxf(.02f,-dx*nx-dy*ny-dz*nz);float fresnel=water_fresnel(nv);float light=.55f+.45f*fmaxf(0.0f,nx*lx+ny*ly+nz*lz);float deep=1.0f-expf(-waterDepth*.23f);float r=.10f-deep*.065f;float g=.56f-deep*.30f;float b=.56f-deep*.16f;if(info.z<.5f){r+=.035f;g-=.045f;b-=.08f;}
float tone=wave>.4f?1.08f:wave<-.4f?.92f:1.0f;float band=1.0f+(tone-1.0f)*fade;r*=light*band;g*=light*band;b*=light*band;float reflection=fminf(.85f,fresnel);r=r*(1.0f-reflection)+.40f*reflection;g=g*(1.0f-reflection)+.67f*reflection;b=b*(1.0f-reflection)+.80f*reflection;
float hx=lx-dx;float hy=ly-dy;float hz=lz-dz;float hl=sqrtf(hx*hx+hy*hy+hz*hz);float highlight=powf(fmaxf(0.0f,(nx*hx+ny*hy+nz*hz)/fmaxf(.01f,hl)),96.0f)*.35f*fade;
float foam=(1.0f-fminf(1.0f,waterDepth/1.0f))*(.55f+.45f*sinf(u*2.0f+v*.7f-time));foam=foam>.5f?.65f:0.0f;float footprint=closest*tangent*2.0f/(float)h/fmaxf(.08f,-dy);float strokeFade=1.0f/(1.0f+footprint*footprint*16.0f);float fleck=noise3(u*.8f-drift*.3f,8.0f,v*1.8f);float strokes=fmaxf(0.0f,fleck-.65f)*.10f*fade*strokeFade*(1.0f+rain);float skyDim=1.0f-rain*.25f;r=(r+highlight+strokes)*skyDim;g=(g+highlight+strokes)*skyDim;b=(b+highlight+strokes)*skyDim;r=r*(1.0f-foam)+.78f*foam;g=g*(1.0f-foam)+.91f*foam;b=b*(1.0f-foam)+.85f*foam;
// Beer-Lambert attenuation along the viewing ray, rather than a fixed opacity.
// Keep surface reflection and foam visible even in transparent shallows.
float pathLength=waterDepth/fmaxf(.08f,-dy);if(depth[i]!=4294967295u)pathLength=fmaxf(0.0f,(float)depth[i]/(1000.0f*fmaxf(.001f,forward))-closest);
float absorption=info.z<.5f?.55f:info.z<1.5f?.32f:.22f;
float transmission=expf(-pathLength*absorption)*(1.0f-reflection)*(1.0f-foam);if(depth[i]==4294967295u)transmission=0.0f;unsigned int old=pixels[i];r=r*(1.0f-transmission)+(float)(old&255u)/255.0f*transmission;g=g*(1.0f-transmission)+(float)((old>>8)&255u)/255.0f*transmission;b=b*(1.0f-transmission)+(float)((old>>16)&255u)/255.0f*transmission;
depth[i]=key;picks[i]=0u;pixels[i]=(unsigned int)(fminf(1.0f,r)*255.0f)|((unsigned int)(fminf(1.0f,g)*255.0f)<<8)|((unsigned int)(fminf(1.0f,b)*255.0f)<<16)|4278190080u;
}
