import {planOutline} from './plan-model.js';
export const MAX_WATER_PLANES=32;
export function defaultWater(){return {ocean:{enabled:false,level:0},planes:[],weather:{windDirection:45,windSpeed:4,rain:0}};}
export function validateWater(value){const w=value??defaultWater();const finite=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;
if(!w.ocean||typeof w.ocean.enabled!=='boolean'||!finite(w.ocean.level,-256,2048))throw Error('Invalid ocean level.');
if(!Array.isArray(w.planes)||w.planes.length>MAX_WATER_PLANES)throw Error('Up to 32 water planes are supported.');
const ids=new Set();const planes=w.planes.map(p=>{if(!p||!Number.isInteger(p.id)||p.id<1||ids.has(p.id)||typeof p.name!=='string'||p.name.length>80||typeof p.visible!=='boolean'||!['pond','lake','ocean'].includes(p.kind))throw Error('Invalid water plane.');ids.add(p.id);for(const k of ['x','z'])if(!finite(p[k],-65536,65536))throw Error('Invalid water position.');if(!finite(p.level,-256,2048)||!finite(p.width,1,65536)||!finite(p.length,1,65536)||!finite(p.rotation,0,360))throw Error('Invalid water dimensions.');return {id:p.id,name:p.name,visible:p.visible,kind:p.kind,x:p.x,z:p.z,level:p.level,width:p.width,length:p.length,rotation:p.rotation};});
const weather=w.weather??defaultWater().weather;if(!finite(weather.windDirection,0,360)||!finite(weather.windSpeed,0,30)||!finite(weather.rain,0,1))throw Error('Invalid water weather.');return {ocean:{enabled:w.ocean.enabled,level:w.ocean.level},planes,weather:{...weather}};}
export function packWater(water){const rows=[];if(water.ocean.enabled)rows.push(0,0,0,0,water.ocean.level,0,2,1);for(const p of water.planes)if(p.visible)rows.push(p.x,p.z,p.width*.5,p.length*.5,p.level,p.rotation*Math.PI/180,p.kind==='ocean'?2:p.kind==='lake'?1:0,1);return new Float32Array(rows);}

export function packSurfaces(water,plans=[]){const rows=Array.from(packWater(water)),points=new Float32Array(49*128*4);for(const p of plans){if(p.type!=='water'||!p.visible)continue;const outline=planOutline(p);const index=rows.length/8;const xs=outline.map(v=>v.x),zs=outline.map(v=>v.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);rows.push((minX+maxX)/2,(minZ+maxZ)/2,(maxX-minX)/2,(maxZ-minZ)/2,p.level,0,p.kind==='ocean'?2:p.kind==='lake'?1:0,outline.length);outline.forEach((v,i)=>points.set([v.x,v.z,0,0],(index*128+i)*4));}return {rows:new Float32Array(rows),points};}
