// Adapted from SamG-Coder/clearwater b0c3bdb, MIT (vendor/LICENSE.ClearWater).
// Two 64x64 Stockham inverse FFT cascades, instead of three 256x256 fields.
__device__ float water_length(int c){return c==0?37.0f:149.0f;}
__global__ void water_seed(float4* seed){
 int id=(int)(blockIdx.x*blockDim.x+threadIdx.x);if(id>=8192)return;int c=id/4096;int x=id%64;int z=(id/64)%64;float L=water_length(c);float kx=6.2831853f*(float)(x<32?x:x-64)/L;float kz=6.2831853f*(float)(z<32?z:z-64)/L;float k=sqrtf(kx*kx+kz*kz);float P=0.0f;
 if(k>.00001f){float kp=6.2831853f/(c==0?5.0f:25.0f);float lk=logf(k/kp);float bump=expf(-.5f*lk*lk/.25f);float tail=.025f*expf(-kp*kp/(k*k))*expf(-k*k/(kp*kp*80.0f));float dir=kx/k;P=(bump+tail)*(.22f+.78f*dir*dir)/(k*k*k*k);}
 float radius=sqrtf(-2.0f*logf(fmaxf(.000001f,rnd((unsigned int)id*2u+571u))));float a=6.2831853f*rnd((unsigned int)id*2u+572u);float amp=sqrtf(P*.5f);seed[id]=make_float4(radius*cosf(a)*amp,radius*sinf(a)*amp,kx,kz);
}
__global__ void water_rows(const float4* seed,float* rows){int row=(int)(blockIdx.x*blockDim.x+threadIdx.x);if(row>=128)return;float sum=0.0f;for(int x=0;x<64;x++){float4 a=seed[row*64+x];sum+=2.0f*(a.z*a.z+a.w*a.w)*(a.x*a.x+a.y*a.y);}rows[row]=sum;}
__global__ void water_norm(const float* rows,float* scales){int c=(int)(blockIdx.x*blockDim.x+threadIdx.x);if(c>=2)return;float sum=0.0f;for(int z=0;z<64;z++)sum+=rows[c*64+z];scales[c]=(c==0?.12f:.065f)/sqrtf(fmaxf(.0000001f,sum));}
__global__ void water_evolve(const float4* seed,const float* scales,float4* output,float time,float windSpeed){
 int id=(int)(blockIdx.x*blockDim.x+threadIdx.x);if(id>=8192)return;int c=id/4096;int x=id%64;int z=(id/64)%64;float4 a=seed[id];float4 b=seed[c*4096+((64-z)%64)*64+(64-x)%64];float k=sqrtf(a.z*a.z+a.w*a.w);float omega=sqrtf(9.81f*k);float co=cosf(omega*time);float si=sinf(omega*time);float scale=scales[c]*(.20f+fminf(25.0f,windSpeed)*.12f);float re=((a.x+b.x)*co-(a.y+b.y)*si)*scale;float im=((a.x-b.x)*si+(a.y-b.y)*co)*scale;float kx=x==32?0.0f:a.z;float kz=z==32?0.0f:a.w;
 output[id]=make_float4((1.0f-kx)*re,(1.0f-kx)*im,-kz*im,kz*re);
}
__global__ void water_fft(const float4* input,float4* output,int p,int axis){
 int id=(int)(blockIdx.x*blockDim.x+threadIdx.x);if(id>=8192)return;int c=id/4096;int x=id%64;int z=(id/64)%64;int j=axis==0?x:z;int k=j&(p-1);int i=((j-(j&(2*p-1)))>>1)+k;int ia=c*4096+(axis==0?z*64+i:i*64+x);int ib=ia+(axis==0?32:2048);float4 a=input[ia];float4 b=input[ib];float angle=3.14159265f*(float)k/(float)p;float co=cosf(angle);float si=sinf(angle);float sign=(j&p)!=0?-1.0f:1.0f;output[id]=make_float4(a.x+sign*(co*b.x-si*b.y),a.y+sign*(si*b.x+co*b.y),a.z+sign*(co*b.z-si*b.w),a.w+sign*(si*b.z+co*b.w));
}
__global__ void water_resolve(const float4* input,float4* waves){int id=(int)(blockIdx.x*blockDim.x+threadIdx.x);if(id>=8192)return;int c=id/4096;int x=id%64;int z=(id/64)%64;float4 a=input[id];float gx=(input[c*4096+z*64+(x+1)%64].y-input[c*4096+z*64+(x+63)%64].y)*32.0f/water_length(c);float gz=(input[c*4096+((z+1)%64)*64+x].z-input[c*4096+((z+63)%64)*64+x].z)*32.0f/water_length(c);waves[id]=make_float4(a.x,a.y,a.z,gx+gz);}
__device__ float4 water_sample(const float4* waves,float x,float z,int c){float gx=x*64.0f/water_length(c);float gz=z*64.0f/water_length(c);int ix=(int)floorf(gx);int iz=(int)floorf(gz);float u=gx-floorf(gx);float v=gz-floorf(gz);ix=ix&63;iz=iz&63;float4 a=waves[c*4096+iz*64+ix];float4 b=waves[c*4096+iz*64+(ix+1)%64];float4 d=waves[c*4096+((iz+1)%64)*64+ix];float4 e=waves[c*4096+((iz+1)%64)*64+(ix+1)%64];return make_float4((a.x*(1.0f-u)+b.x*u)*(1.0f-v)+(d.x*(1.0f-u)+e.x*u)*v,(a.y*(1.0f-u)+b.y*u)*(1.0f-v)+(d.y*(1.0f-u)+e.y*u)*v,(a.z*(1.0f-u)+b.z*u)*(1.0f-v)+(d.z*(1.0f-u)+e.z*u)*v,(a.w*(1.0f-u)+b.w*u)*(1.0f-v)+(d.w*(1.0f-u)+e.w*u)*v);}
__device__ float4 water_field(const float4* waves,float x,float z,float angle,float footprint){float u=x*cosf(angle)+z*sinf(angle);float v=-x*sinf(angle)+z*cosf(angle);float4 a=water_sample(waves,u,v,0);float4 b=water_sample(waves,u,v,1);float fine=1.0f/(1.0f+footprint*footprint*.7f);float broad=1.0f/(1.0f+footprint*footprint*.025f);float sx=a.y*fine+b.y*broad;float sz=a.z*fine+b.z*broad;return make_float4(a.x*fine+b.x*broad,sx*cosf(angle)-sz*sinf(angle),sx*sinf(angle)+sz*cosf(angle),a.w*fine+b.w*broad);}
